Repository Zilliqa/Zilliqa, pull requests merged in 2018-09, with the labels that each got.

#551 Staging for K8S testing
  CMakeLists.txt
  constants.xml
  constants_local.xml
  src/cmd/CMakeLists.txt
  src/cmd/Gen_Test_Transaction.cpp
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/depends/common/FixedHash.h
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusCommon.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libData/AccountData/AccountStoreBase.h
  src/libData/AccountData/AccountStoreBase.tpp
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/Transaction.cpp
  src/libData/AccountData/Transaction.h
  src/libData/DataStructures/MultiIndexContainer.h
  src/libDirectoryService/CMakeLists.txt
  src/libDirectoryService/Coinbase.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/CMakeLists.txt
  src/libNode/Coinbase.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
  src/libServer/Server.cpp
  src/libUtils/GetTxnFromFile.h
  src/libUtils/RsyncThread.h
  src/libUtils/TxnRootComputation.cpp
  src/libUtils/TxnRootComputation.h
  src/libValidator/Validator.cpp
  src/libValidator/Validator.h
  src/libZilliqa/Zilliqa.cpp
  tests/Data/CMakeLists.txt
  tests/Data/Test_Get_Txn.cpp
  tests/Data/Test_MultiIndex.cpp
  tests/Node/test_gentxn.sh
  tests/Zilliqa/test_zilliqa_lookup.py
Labels: Ready

#546 Improvement on State Delta for Contract
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/Account.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStoreTemp.cpp
Labels: Ready

#554 Fix potential crash problem
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
Labels: Ready, enhancement

#559 Accumulative fixes
  .github/PULL_REQUEST_TEMPLATE.md
  tests/Node/watch_node_simple.sh
Labels: Ready

#560 Improve insertion performance of MultiIndexContainer
  src/libData/DataStructures/MultiIndexContainer.h
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  tests/Data/Test_MultiIndex.cpp
Labels: Ready, enhancement

#536 Implementation of Transaction Receipt phase I
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libConsensus/ConsensusCommon.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libData/AccountData/AccountStoreBase.h
  src/libData/AccountData/AccountStoreBase.tpp
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/CMakeLists.txt
  src/libData/AccountData/LogEntry.cpp
  src/libData/AccountData/LogEntry.h
  src/libData/AccountData/TransactionReceipt.cpp
  src/libData/AccountData/TransactionReceipt.h
  src/libData/BlockData/Block/TxBlock.cpp
  src/libData/BlockData/BlockHeader/BlockHashSet.h
  src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
  src/libData/BlockData/BlockHeader/MicroBlockHeader.h
  src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.h
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Synchronizer.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libServer/JSONConversion.cpp
  src/libServer/JSONConversion.h
  src/libServer/Server.cpp
  src/libUtils/JsonUtils.h
  src/libUtils/TxnRootComputation.cpp
  src/libUtils/TxnRootComputation.h
  src/libValidator/Validator.cpp
  src/libValidator/Validator.h
  tests/Data/Test_Contract.cpp
  tests/Data/Test_ContractInvoke.cpp
  tests/Lookup/Test_LookupNodeForTxBlock.cpp
  tests/Persistence/Test_TxBody.cpp
  tests/Persistence/Test_TxPersistence.cpp
Labels: dependent

#557 Transaction generation and dispatcher improvement
  constants.xml
  constants_local.xml
  src/cmd/CMakeLists.txt
  src/cmd/Gen_Test_Transaction.cpp
  src/cmd/gentxn.cpp
  src/common/Constants.cpp
  src/libLookup/Lookup.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libUtils/GetTxnFromFile.h
  tests/Node/test_gentxn.sh
  tests/Zilliqa/test_zilliqa_lookup.py
Labels: Ready

#544 Release helper for upgrading protocol
  CMakeLists.txt
  VERSION
  release.sh
  src/cmd/CMakeLists.txt
  src/cmd/signmultisig.cpp
Labels: Ready, enhancement

#565 Add XML checker
  .travis.yml
  constants.xml
  constants_local.xml
  scripts/ci_install_deps.sh
  scripts/ci_xml_checker.sh
Labels: Ready

#563 Handling Finalblock Consensus Error due to Missing Microblocks
  src/common/Messages.h
  src/libData/AccountData/LogEntry.cpp
  src/libData/BlockData/Block/MicroBlock.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
Labels: Ready

#567 Remove 'using namespace' in header files
  .clang-tidy
  cmake/LLVMExtraTools.cmake
  scripts/ci_build.sh
  scripts/ci_install_deps.sh
  scripts/run-clang-tidy.py
  src/cmd/gentxn.cpp
  src/libConsensus/ConsensusBackup.h
  src/libConsensus/ConsensusLeader.h
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/Account.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libData/AccountData/AccountStoreAtomic.tpp
  src/libData/AccountData/AccountStoreBase.h
  src/libData/AccountData/AccountStoreBase.tpp
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/AccountStoreTemp.cpp
  src/libData/AccountData/AccountStoreTrie.h
  src/libData/AccountData/AccountStoreTrie.tpp
  src/libData/BlockChainData/BlockChain.h
  src/libData/BlockData/BlockHeader/TxBlockHeader.h
  src/libPersistence/BlockStorage.h
  src/libPersistence/ContractStorage.cpp
  src/libPersistence/ContractStorage.h
  src/libUtils/TimeLockedFunction.h
  src/libUtils/TxnRootComputation.cpp
Labels: Ready

#569 Fix difficulty adjust continually after 1 year epoch problem
  src/libDirectoryService/DirectoryService.cpp
Labels: Ready

#545 Dual PoW difficulty levels for DS committee and shards
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Synchronizer.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  tests/Lookup/Test_LookupNodeForDSBlock.cpp
  tests/Lookup/Test_LookupNodeForTxBlock.cpp
  tests/Node/test_node_server.sh
  tests/Node/test_node_simple.sh
  tests/Persistence/Test_DSPersistence.cpp
  tests/Zilliqa/test_zilliqa_local.py
Labels: Ready, enhancement

#572 Shard size calculator
  src/libUtils/CMakeLists.txt
  src/libUtils/ShardSizeCalculator.cpp
  src/libUtils/ShardSizeCalculator.h
  tests/Utils/CMakeLists.txt
  tests/Utils/Test_ShardSizeCalculator.cpp
Labels: Ready, enhancement

#558 Download procedure for upgrading protocol
  docker/Dockerfile
  release.sh
  scripts/ci_install_deps.sh
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libMediator/Mediator.h
  src/libUtils/CMakeLists.txt
  src/libUtils/SWInfo.cpp
  src/libUtils/SWInfo.h
  src/libUtils/UpgradeManager.cpp
  src/libUtils/UpgradeManager.h
  tests/Utils/CMakeLists.txt
  tests/Utils/Test_UpgradeManager.cpp
Labels: Ready, enhancement

#578 Dual difficulty adjustment
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  tests/POW/CMakeLists.txt
  tests/POW/test_POW.cpp
Labels: Ready

#580 [Refactor] Add protobuf messages for Lookup
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
Labels: Ready

#579 [clang-tidy] Use range-based for-loop preferably
  .clang-tidy
  src/cmd/sendcmd.cpp
  src/libData/AccountData/AccountStore.cpp
  src/libDirectoryService/DSBlockMessage.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNetwork/PeerStore.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  tests/Persistence/Test_DSPersistence.cpp
  tests/Persistence/Test_TxPersistence.cpp
Labels: Ready

#573 TxnPacket/FBCons buffer refactoring & introduce MBCons Buffer
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
Labels: Ready

#584 Remove 'using namespace std' in Miner.h
  src/depends/common/Miner.h
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libMediator/Mediator.h
  src/libNode/Node.h
  src/libPersistence/Retriever.cpp
  src/libUtils/GetTxnFromFile.h
  src/libUtils/HashUtils.h
  src/libZilliqa/Zilliqa.h
Labels: Ready

#582 [clang-tidy] Simplify boolean expression
  .clang-tidy
  src/common/Constants.cpp
  src/libConsensus/ConsensusBackup.cpp
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusLeader.cpp
  src/libConsensus/ConsensusUser.cpp
  src/libCrypto/MultiSig.cpp
  src/libData/AccountData/Transaction.cpp
  src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNetwork/PeerManager.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libPOW/pow.cpp
  src/libUtils/DetachedFunction.h
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#594 Remove obselete constants
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
Labels: Ready, enhancement

#593 Fix build error after remove "using namespace std" in Miner.h
  src/depends/libethash-cl/CLMiner.cpp
  src/depends/libethash-cl/CLMiner.h
  src/depends/libethash-cuda/CUDAMiner.cpp
  src/depends/libethash-cuda/CUDAMiner.h
Labels: Ready

#599 Deserialization error fix due to wrong offset.
  src/libDirectoryService/MicroBlockProcessing.cpp
Labels: bug

#596 Delay setting DSBlock consensus structures until after consensus is done
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libNode/DSBlockProcessing.cpp
Labels: bug

#620 Make protobuf message for MicroBlock
  src/libMessage/Messenger.cpp
  src/libMessage/ZilliqaMessage.proto
Labels: Ready

#616 Fix interruption caused by late ProcessFinalBlockConsensus
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready

#622 Add ThreadSanitizer and Address Sanitizer option to build system
  CMakeLists.txt
  build.sh
Labels: enhancement

#617 Disallow bootstrap function after blockchain started
  src/libDirectoryService/DirectoryService.cpp
  src/libLookup/Lookup.cpp
  src/libNode/PoWProcessing.cpp
Labels: Ready

#618 Support using multiple GPUs to do mining together
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/depends/common/Miner.h
  src/depends/libethash-cl/CLMiner.cpp
  src/depends/libethash-cl/CLMiner.h
  src/depends/libethash-cuda/CUDAMiner.cpp
  src/depends/libethash-cuda/CUDAMiner.h
  src/libPOW/pow.cpp
  src/libPOW/pow.h
Labels: Ready

#624 Removal of Txbody DB (obsolete)
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libPersistence/Retriever.cpp
  src/libPersistence/Retriever.h
  tests/Persistence/Test_TxBody.cpp
Labels: Ready, enhancement

#632 View change hotfix, DS microblock timeout state transition fix and additional debug logs
  src/libDirectoryService/Coinbase.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
Labels: Ready, bug
