Repository Zilliqa/Zilliqa, pull requests merged in 2018-10, with the labels that each got.

#626 Fallback Solution
  CMakeLists.txt
  build.sh
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/libData/BlockChainData/BlockChain.h
  src/libData/BlockData/Block.h
  src/libData/BlockData/Block/CMakeLists.txt
  src/libData/BlockData/Block/FallbackBlock.cpp
  src/libData/BlockData/Block/FallbackBlock.h
  src/libData/BlockData/Block/TxBlock.cpp
  src/libData/BlockData/BlockHeader/BlockHashSet.h
  src/libData/BlockData/BlockHeader/CMakeLists.txt
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.cpp
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.h
  src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
  src/libData/BlockData/BlockHeader/VCBlockHeader.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ShardStruct.h
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMediator/Mediator.cpp
  src/libMediator/Mediator.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/CMakeLists.txt
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
  src/libServer/Server.cpp
  src/libUtils/GetTxnFromFile.h
Labels: Ready

#581 Integration for upgrading protocol
  README.md
  VERSION
  constants.xml
  constants_local.xml
  release.sh
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libMediator/Mediator.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libPersistence/Retriever.cpp
  src/libUtils/SWInfo.cpp
  src/libUtils/SWInfo.h
  src/libUtils/UpgradeManager.cpp
  src/libUtils/UpgradeManager.h
Labels: Ready, enhancement

#636 P2pComm Network layer - manager/wrapper for gossip library
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNetwork/CMakeLists.txt
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
  src/libNetwork/Peer.cpp
  src/libNetwork/Peer.h
  src/libNetwork/RumorManager.cpp
  src/libNetwork/RumorManager.h
  src/libRumorSpreading/Message.h
Labels: Ready

#610 Heartbeat Feature
  CMakeLists.txt
  build.sh
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libLookup/Lookup.h
  src/libMediator/Mediator.cpp
  src/libMediator/Mediator.h
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#639 Enable SHA-256 verification for upgrading protocol
  release.sh
  src/libUtils/UpgradeManager.cpp
Labels: Ready, enhancement

#638 Put block number in consensus message and validate it
  src/libConsensus/ConsensusBackup.cpp
  src/libConsensus/ConsensusBackup.h
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusCommon.h
  src/libConsensus/ConsensusLeader.cpp
  src/libConsensus/ConsensusLeader.h
  src/libConsensus/ConsensusUser.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.h
Labels: Ready

#637 Usecases of Gossip Protocol
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/depends/CMakeLists.txt
  src/libConsensus/ConsensusLeader.cpp
  src/libConsensus/ConsensusLeader.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libNetwork/RumorManager.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: in-progress

#642 Fix CheckStateRoot
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libData/AccountData/AccountStoreBase.h
  src/libData/AccountData/AccountStoreBase.tpp
  src/libData/AccountData/AccountStoreTrie.h
  src/libData/AccountData/AccountStoreTrie.tpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready

#621 Support for Archival Nodes 2
  src/common/Messages.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.h
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
Labels: Ready

#643 Upgrading protocol on look-up nodes
  constants.xml
  constants_local.xml
  release.sh
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/Node.cpp
  src/libUtils/UpgradeManager.cpp
Labels: Ready, enhancement

#644 Verify block hash in consensus to enhance security
  src/libData/BlockData/BlockHeader/BlockHeaderBase.cpp
  src/libData/BlockData/BlockHeader/BlockHeaderBase.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libData/BlockData/BlockHeader/TxBlockHeader.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready

#595 Elect multiple members into DS committee
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libConsensus/ConsensusLeader.cpp
  src/libData/BlockData/Block/DSBlock.cpp
  src/libData/BlockData/Block/DSBlock.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Synchronizer.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.h
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libServer/JSONConversion.cpp
  tests/Lookup/Test_LookupNodeForDSBlock.cpp
  tests/Lookup/Test_LookupNodeForTxBlock.cpp
  tests/Node/test_node_simple.sh
  tests/Persistence/ReadBlock.cpp
  tests/Persistence/Test_DSPersistence.cpp
Labels: Ready, enhancement

#650 Treebased Cluster Broadcasting
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/ViewChangeBlockProcessing.cpp
Labels: Ready, enhancement

#658 Fix substraction underflow issue in gas calculation
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#657 Miscellaneous fixes on build system
  CMakeLists.txt
  build.sh
  scripts/ci_xml_checker.sh
  tests/.gitignore
Labels: Ready, enhancement

#661 Hotfix for ci_xml_checker.sh issue in build.sh
  build.sh
Labels: Ready, bug

#663 Added ProtoTxBlock
  src/libData/BlockData/Block/TxBlock.cpp
  src/libData/BlockData/Block/TxBlock.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/ZilliqaMessage.proto
Labels: Ready

#668 Changed data block types serialization to completely use Messenger
  src/common/Serializable.h
  src/libDB/ArchiveDB.cpp
  src/libDB/ArchiveDB.h
  src/libData/BlockData/Block/BlockBase.cpp
  src/libData/BlockData/Block/BlockBase.h
  src/libData/BlockData/Block/DSBlock.cpp
  src/libData/BlockData/Block/DSBlock.h
  src/libData/BlockData/Block/FallbackBlock.cpp
  src/libData/BlockData/Block/FallbackBlock.h
  src/libData/BlockData/Block/MicroBlock.cpp
  src/libData/BlockData/Block/MicroBlock.h
  src/libData/BlockData/Block/TxBlock.cpp
  src/libData/BlockData/Block/TxBlock.h
  src/libData/BlockData/Block/VCBlock.cpp
  src/libData/BlockData/Block/VCBlock.h
  src/libData/BlockData/BlockHeader/BlockHeaderBase.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.cpp
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.h
  src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
  src/libData/BlockData/BlockHeader/MicroBlockHeader.h
  src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.h
  src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
  src/libData/BlockData/BlockHeader/VCBlockHeader.h
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/Node.h
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libUtils/HashUtils.h
Labels: Ready

#660 Stop Timing for Fallback if PoW Failed & Other fixes & Add checkers & CheckStateRoot in every epoch
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDB/Archival.cpp
  src/libData/AccountData/AccountStoreBase.tpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
Labels: Ready

#676 Hotfix of g3log installation failed
  CMakeLists.txt
Labels: bug

#677 Added hashing functions to Messenger for the DSBlockHashSet
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
Labels: Ready

#264 Integeration of daemon with Zilliqa dir
  CMakeLists.txt
  cmake/LLVMExtraTools.cmake
  daemon/CMakeLists.txt
  daemon/ZilliqaDaemon.cpp
  daemon/ZilliqaDaemon_AWS.cpp
  daemon/run.sh
  daemon/run_local.sh
  tests/Zilliqa/daemon_restart.py
  tests/Zilliqa/daemon_restart_local.py
Labels: Ready, enhancement

#664 Benchmarking of gossip
  src/libNetwork/RumorManager.cpp
  src/libNetwork/RumorManager.h
  src/libRumorSpreading/RumorHolder.cpp
  src/libRumorSpreading/RumorStateMachine.cpp
Labels: Ready

#669 Benchmarking of TreeBased Cluster Broadcasting
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libNode/Node.cpp
Labels: Ready

#659 Develop verify lookup node and messages
  constants.xml
  constants_local.xml
  src/common/Messages.h
  src/libDirectoryService/DirectoryService.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libLookup/Synchronizer.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/Node.cpp
  tests/Zilliqa/test_zilliqa_lookup.py
Labels: Ready

#674 DS to send vcds message instead of vc block (before ds block consensus) to shard nodes
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/ViewChangeBlockProcessing.cpp
Labels: Ready, enhancement

#679 Added CommitteeHash to BlockHeaderBase and Messenger
  src/libData/BlockData/BlockHeader/BlockHashSet.h
  src/libData/BlockData/BlockHeader/BlockHeaderBase.cpp
  src/libData/BlockData/BlockHeader/BlockHeaderBase.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.cpp
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.h
  src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
  src/libData/BlockData/BlockHeader/MicroBlockHeader.h
  src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.h
  src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
  src/libData/BlockData/BlockHeader/VCBlockHeader.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Synchronizer.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  tests/Lookup/Test_LookupNodeForDSBlock.cpp
  tests/Lookup/Test_LookupNodeForTxBlock.cpp
  tests/Persistence/Test_DSPersistence.cpp
  tests/Persistence/Test_TxPersistence.cpp
Labels: Ready

#683 Random shard leader selection
  src/libDB/ExplorerDB.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libLookup/Lookup.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libUtils/DataConversion.cpp
  src/libUtils/DataConversion.h
  src/libUtils/HashUtils.h
Labels: Ready

#685 Fix new node cannot join problem
  src/libMessage/Messenger.cpp
  src/libNode/PoWProcessing.cpp
Labels: Ready, bug

#686 Spec. change of COMM_SIZE
  constants.xml
  constants_local.xml
  src/libMediator/Mediator.cpp
  src/libUtils/ShardSizeCalculator.cpp
  tests/Utils/Test_ShardSizeCalculator.cpp
Labels: Ready, bug

#687 Added DSBlockHeader hashes verification
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libNode/DSBlockProcessing.cpp
Labels: Ready

#681 Directory Blocks Persistance Storage
  src/common/Messages.h
  src/libData/BlockChainData/BlockLinkChain.h
  src/libData/BlockData/Block/CMakeLists.txt
  src/libData/BlockData/Block/FallbackBlockWShardingStructure.cpp
  src/libData/BlockData/Block/FallbackBlockWShardingStructure.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libLookup/Synchronizer.cpp
  src/libMediator/Mediator.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
Labels: Ready

#655 Test lib crypto
  tests/Crypto/Test_MultiSig.cpp
  tests/Crypto/Test_Schnorr.cpp
  tests/Crypto/Test_Sha2.cpp
  tests/Crypto/Test_Sha3.cpp
Labels: Ready, enhancement

#690 Fix hardcoded DS block hash in Micro block
  src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
  src/libData/BlockData/BlockHeader/MicroBlockHeader.h
  src/libMessage/Messenger.cpp
  src/libMessage/ZilliqaMessage.proto
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready, bug

#688 Made protobuf-equivalent message for transaction (still unused)
  README.md
  src/libData/AccountData/Transaction.cpp
  src/libData/AccountData/Transaction.h
  src/libMessage/Messenger.cpp
  src/libMessage/ZilliqaMessage.proto
Labels: Ready

#693 Fix DoS when Schnorr deserialization failed
  src/libCrypto/Schnorr.cpp
  tests/Crypto/Test_Schnorr.cpp
Labels: Ready, bug

#689 Implementation of Gas Rewards
  constants.xml
  constants_local.xml
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusCommon.h
  src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
  src/libData/BlockData/BlockHeader/MicroBlockHeader.h
  src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.h
  src/libDirectoryService/Coinbase.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libLookup/Synchronizer.cpp
  src/libMediator/Mediator.cpp
  src/libMediator/Mediator.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
  src/libServer/JSONConversion.cpp
  tests/Lookup/Test_LookupNodeForTxBlock.cpp
  tests/Persistence/Test_TxPersistence.cpp
Labels: Ready

#700 Removed the deprecated function SignReponse
  src/libCrypto/MultiSig.cpp
Labels: Ready, enhancement

#699 Remove insecure function `memcpy` in libPoW and add unit tests
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  tests/POW/test_POW.cpp
Labels: Ready, enhancement

#702 Check for null consensus object in consensus user
  src/libConsensus/ConsensusUser.cpp
Labels: Ready, bug, enhancement

#698 Fix CheckStateRoot Failure After View Change
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready

#703 Add max depth for contract call
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#707 Hot fix to downgrade urllib3 for kube 7.0 support
  scripts/ci_make_image.sh
Labels: bug

#695 Enable verification of PoW ordering to check the sharding structure from DS leader
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/PoWProcessing.cpp
Labels: Ready, help wanted

#706 No. of txns in MicroBlock are no more limited to MAXSUBMITTXNPERNODE*Shard_Size
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready

#696 Add checker of CommiteeHash for Tx/FB/VC/Micro blocks
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusCommon.h
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.h
  src/libNode/ViewChangeBlockProcessing.cpp
Labels: Ready

#692 DS info verification
  src/libDB/Archival.cpp
  src/libData/BlockChainData/BlockLinkChain.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libLookup/Synchronizer.cpp
  src/libLookup/Synchronizer.h
  src/libMediator/Mediator.cpp
  src/libMediator/Mediator.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/CMakeLists.txt
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libValidator/CMakeLists.txt
  src/libValidator/Validator.cpp
  src/libValidator/Validator.h
Labels: Ready

#705 Process the console prints when the execution of contract failed
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
Labels: Ready

#704 Support user select use which GPU for mine
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libPOW/pow.cpp
  src/libPOW/pow.h
Labels: Ready

#712 Fix - DSLD node drops out when not enough commit received for Final Block Consensus
  src/libConsensus/ConsensusLeader.cpp
Labels: Ready, bug

#726 [testnetv3-dev] Fix broadcast hash insertion and other testnet-discovered issues
  src/libConsensus/ConsensusBackup.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libNetwork/P2PComm.cpp
Labels: Ready

#727 Fix broadcast hash insertion and other testnet-discovered issues
  src/libConsensus/ConsensusBackup.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libNetwork/P2PComm.cpp
Labels: Ready

#731 Remove SHA3
  src/depends/CMakeLists.txt
  src/depends/Sha3/CMakeLists.txt
  src/depends/Sha3/Sha3.c
  src/libCrypto/CMakeLists.txt
  src/libCrypto/Sha3.cpp
  src/libCrypto/Sha3.h
  tests/Crypto/CMakeLists.txt
  tests/Crypto/Test_Sha3.cpp
Labels: Ready

#724 [testnetv3-dev] Optimize the logs for production run
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
Labels: Ready

#732 Fix lookup node use 100% cpu problem
  src/libNetwork/P2PComm.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#713 Replace MultiIndexContainer with TxnPool
  src/common/Messages.h
  src/libData/AccountData/TxnPool.h
  src/libData/DataStructures/MultiIndexContainer.h
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  tests/Data/CMakeLists.txt
  tests/Data/Test_MultiIndex.cpp
Labels: Ready

#734 [testnetv3-dev]Move the check for initialization to correct place
  src/libMessage/Messenger.cpp
Labels: Ready

#736 [testnetv3-dev] Fix lookup cpu usage 100% problem
  src/libNetwork/P2PComm.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#745 Rename COPYRIGHT to LICENSE
  COPYRIGHT
  LICENSE
  build.sh
  scripts/ci_build.sh
  scripts/license_checker.sh
Labels: enhancement

#747 Check to avoid buffering Final block consensus msg when am non-ds node
  src/libDirectoryService/FinalBlockPostProcessing.cpp
Labels: Ready

#749 [testnetv3-dev] Check to avoid buffering Final block consensus msg when am non-ds node
  src/libDirectoryService/FinalBlockPostProcessing.cpp
Labels: Ready

#748 Adjust the order of check for DSBlock CommHash in ProcessVCDS
  src/libNode/DSBlockProcessing.cpp
Labels: Ready, bug

#755 [testnetv3-dev] Adjust the order of VCDS check for DSBlock CommHash
  src/libNode/DSBlockProcessing.cpp
Labels: Ready, bug

#742 Robust consensus using subsets
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libConsensus/ConsensusBackup.cpp
  src/libConsensus/ConsensusBackup.h
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusCommon.h
  src/libConsensus/ConsensusLeader.cpp
  src/libConsensus/ConsensusLeader.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
Labels: Ready

#760 Bound the message size in ProcessPingAll
  src/libNetwork/PeerManager.cpp
Labels: Ready

#763 Change misleading variable name in blocklinkchain
  src/libData/BlockChainData/BlockLinkChain.h
Labels: Ready

#766 Put upgrade location to constant file
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libUtils/UpgradeManager.cpp
Labels: Ready

#768 [testnetv3-dev] Fix the Bad Pow Ordering
  src/libDirectoryService/DSBlockPreProcessing.cpp
Labels: Ready

#772 Avoid buffering of FB while in MBSUBMISSION or VC State
  src/libDirectoryService/FinalBlockPostProcessing.cpp
Labels: Ready

#770 [testnetv3-dev] Moved the logging for DEBUG mode only.
  src/libNetwork/PeerManager.cpp
  src/libNetwork/RumorManager.cpp
  src/libRumorSpreading/RumorHolder.cpp
Labels: Ready

#773 Moved the logging for DEBUG mode only.
  src/libNetwork/PeerManager.cpp
  src/libNetwork/RumorManager.cpp
  src/libRumorSpreading/RumorHolder.cpp
Labels: Ready

#771 Fix the Bad Pow Ordering
  src/libDirectoryService/DSBlockPreProcessing.cpp
Labels: Ready

#776 Improve comparison operator
  src/libData/AccountData/Transaction.cpp
  src/libData/BlockData/Block/DSBlock.cpp
  src/libData/BlockData/Block/FallbackBlock.cpp
  src/libData/BlockData/Block/MicroBlock.cpp
  src/libData/BlockData/Block/TxBlock.cpp
  src/libData/BlockData/Block/VCBlock.cpp
  src/libData/BlockData/BlockHeader/BlockHashSet.h
  src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.h
  src/libMessage/Messenger.cpp
  src/libMessage/ZilliqaMessage.proto
Labels: Ready

#781 Fix a bug in blockchain where in the index 0 for not being pushed
  src/libData/BlockChainData/BlockLinkChain.h
Labels: Ready, bug

#787 [testnetv3-dev] Avoid dispatching same messages when gossip is not running
  src/libNetwork/RumorManager.cpp
  src/libNetwork/RumorManager.h
Labels: Ready

#786 Move PoW ordering tolerance into the constants file
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
Labels: Ready

#790 Change docker registry region
  scripts/ci_make_image.sh
  scripts/make_image.sh
Labels: Ready, high

#784 Upgrade/release should refer to account/repo defined in constant file for binary host
  constants.xml
  constants_local.xml
  daemon/ZilliqaDaemon_AWS.cpp
  release.sh
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libUtils/UpgradeManager.cpp
Labels: Ready, bug

#753 Validation of Tx Blocks recvd from Lookup
  src/libData/BlockChainData/BlockLinkChain.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libValidator/Validator.cpp
  src/libValidator/Validator.h
Labels: Ready

#785 [testnetv3-dev] Move PoW ordering tolerance into the constants file
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
Labels: Ready
