Repository Zilliqa/Zilliqa, pull requests merged in 2018-07, with the labels that each got.

#390 Update testnet codename to D24
  README.md
Labels: bug

#392 Minor fix on Consensus Failure checking
  src/libNode/FinalBlockProcessing.cpp
Labels: high

#397 Fix bug for execution with failed transaction & Fix problem with RejoinAsDS in DS Epoch
  src/common/Constants.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNetwork/Whitelist.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libPersistence/Retriever.cpp
Labels: bug, high

#399 Combine response of MissingTxn in single message & Fix double lock & Clean Logs
  README.md
  src/libConsensus/ConsensusUser.cpp
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStoreSC.tpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ShardingPostProcessing.cpp
  src/libNetwork/P2PComm.cpp
  src/libNetwork/PeerManager.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/ShardingInfoProcessing.cpp
  src/libPOW/pow.cpp
  src/libServer/Server.cpp
  src/libUtils/TimeLockedFunction.h
  src/libValidator/Validator.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: bug, high

#409 Reordered block number checking in EthashConfigureLightClient
  src/libPOW/pow.cpp
Labels: bug

#407 Fixed the port range check
  src/depends/NAT/nat.cpp
Labels: bug

#410 Fixes/consensus out of order messages
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libConsensus/ConsensusBackup.cpp
  src/libConsensus/ConsensusBackup.h
  src/libConsensus/ConsensusLeader.cpp
Labels: enhancement, high

#408 Fix blocking ProcessSubmitTransaction for node doing rejoining
  constants.xml
  constants_local.xml
  src/cmd/sendcmd.cpp
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/depends/libDatabase/LevelDB.cpp
  src/libLookup/Lookup.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoW2Processing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/Retriever.cpp
Labels: high

#411 Use only 1 thread to handle to-be-removed broadcast messages
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
  src/libUtils/ThreadPool.h
  tests/Network/Test_P2PComm.cpp
Labels: enhancement, high

#415 Solidating Synchronization between Microblock and Finalblock
  src/libData/BlockData/Block/TxBlock.cpp
  src/libData/BlockData/Block/TxBlock.h
  src/libData/BlockData/BlockHeader/BlockHashSet.h
  src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
  src/libData/BlockData/BlockHeader/MicroBlockHeader.h
  src/libData/BlockData/BlockHeader/UnavailableMicroBlock.h
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libLookup/Synchronizer.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  tests/Lookup/Test_LookupNodeForTxBlock.cpp
  tests/Persistence/Test_TxPersistence.cpp
Labels: Ready, bug, high

#418 Remove TxHashes in Microblock sending to DS
  src/libData/BlockData/Block/MicroBlock.cpp
  src/libData/BlockData/Block/MicroBlock.h
  src/libData/BlockData/BlockHeader/BlockHashSet.h
  src/libData/BlockData/BlockHeader/UnavailableMicroBlock.h
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.h
Labels: Ready, enhancement, medium

#419 Resolve microblock consensus message being processed in an out of order manner
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libConsensus/ConsensusBackup.cpp
  src/libConsensus/ConsensusBackup.h
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusCommon.h
  src/libConsensus/ConsensusUser.cpp
  src/libConsensus/ConsensusUser.h
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.h
Labels: bug, enhancement, high

#416 Moved sharing assignments from FINALBLOCK to SHARDING
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ShardingPostProcessing.cpp
  src/libDirectoryService/ShardingPreProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.h
  src/libNode/ShardingInfoProcessing.cpp
Labels: Ready, enhancement

#401 Apply conditional variable for sleep()
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPersistence/Retriever.cpp
Labels: medium

#425 Implement consensus error number and message
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusCommon.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
Labels: enhancement, high

#423 Call notify_all to cv_processConsensusMessage
  src/libConsensus/ConsensusUser.cpp
  src/libConsensus/ConsensusUser.h
  src/libData/BlockChainData/DSBlockChain.cpp
  src/libData/BlockChainData/TxBlockChain.cpp
  src/libData/BlockChainData/VCBlockChain.cpp
  src/libData/DataStructures/CircularArray.h
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.h
  src/libServer/Server.cpp
  tests/Data/Test_CircularArray.cpp
Labels: Ready, bug, high

#369 Small refactoring. no functional change
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
  src/libUtils/Logger.h
Labels: in-progress, medium

#428 Consensus message ordering for ds block, sharding structure, final block and view change block
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/ShardingPostProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
Labels: enhancement

#429 Improve log readability by showing state strings
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusCommon.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/ShardingPostProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: enhancement

#434 Add scripts/make_image.sh for local image build and push
  .travis.yml
  docker/Dockerfile
  scripts/ci_make_image.sh
  scripts/make_image.sh
Labels: Ready

#430 Updates for Scilla
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#435 Create single template class for all blockchain types
  src/common/Constants.h
  src/libData/BlockChainData/BlockChain.h
  src/libData/BlockChainData/CMakeLists.txt
  src/libData/BlockChainData/DSBlockChain.cpp
  src/libData/BlockChainData/DSBlockChain.h
  src/libData/BlockChainData/TxBlockChain.cpp
  src/libData/BlockChainData/TxBlockChain.h
  src/libData/BlockChainData/VCBlockChain.cpp
  src/libData/BlockChainData/VCBlockChain.h
  src/libData/CMakeLists.txt
  src/libDirectoryService/CMakeLists.txt
  src/libLookup/CMakeLists.txt
  src/libLookup/Lookup.cpp
  src/libLookup/Synchronizer.h
  src/libMediator/Mediator.cpp
  src/libMediator/Mediator.h
  src/libNode/Node.h
  src/libPersistence/BlockStorage.h
  src/libServer/CMakeLists.txt
  src/libServer/JSONConversion.cpp
  src/libServer/JSONConversion.h
  tests/Persistence/CMakeLists.txt
Labels: enhancement

#449 Fix/vc ds leader transition
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ShardingPreProcessing.cpp
Labels: bug

#447 Improve make_image.sh and ci_make_image.sh
  constants.xml
  docker/Dockerfile
  scripts/ci_build.sh
  scripts/ci_make_image.sh
  scripts/make_image.sh
Labels: Ready

#450 Fix consensus object not created in certain cases
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/ShardingPreProcessing.cpp
Labels: bug, high

#452 Fix View change cornercase where candidate leader is faulty before vc consensus
  src/libDirectoryService/ViewChangePreProcessing.cpp
Labels: bug, high

#395 Use emplace & emplace_back as more as possible
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusLeader.cpp
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/BlockData/Block/MicroBlock.cpp
  src/libData/BlockData/Block/TxBlock.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/PoW1Processing.cpp
  src/libDirectoryService/PoW2Processing.cpp
  src/libDirectoryService/ShardingPostProcessing.cpp
  src/libDirectoryService/ShardingPreProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNetwork/PeerStore.cpp
  src/libNetwork/Whitelist.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/PoW1Processing.cpp
  src/libNode/ShardingInfoProcessing.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libServer/Server.cpp
  src/libUtils/Scheduler.cpp
  src/libUtils/ThreadPool.h
  src/libValidator/Validator.cpp
  tests/Crypto/Test_MultiSig.cpp
  tests/Data/Test_Block.cpp
  tests/Data/Test_TransactionPerformance.cpp
  tests/Lookup/Test_LookupNodeForDSBlock.cpp
  tests/Network/Test_P2PComm.cpp
  tests/POW/test_POW.cpp
  tests/Persistence/Test_DSPersistence.cpp
  tests/Persistence/Test_TxPersistence.cpp
  tests/Utils/Test_DetachedFunction.cpp
  tests/Utils/Test_JoinableFunction.cpp
  tests/Utils/Test_TxnRootComputation.cpp
  tests/depends/Trie/Test_Trie.cpp
  tests/depends/Trie/Test_TxnTrie.cpp
Labels: Ready, medium

#455 Simplify long checkstate code in DirectoryService
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
Labels: Ready, enhancement

#458 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Ready

#456 Rewrite Node checkstate to match DirectoryService
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready, enhancement

#457 Renamed PoW1 to PoW across all files
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libDirectoryService/CMakeLists.txt
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libMediator/Mediator.h
  src/libNode/CMakeLists.txt
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
  tests/Node/test_node_server.sh
  tests/Node/test_node_simple.sh
  tests/Zilliqa/test_zilliqa_local.py
Labels: Ready, enhancement

#459 Remove unused LASTDSBLOCKREQUEST and LASTDSBLOCKRESPONSE
  src/common/Messages.h
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
Labels: Ready

#461 Enlarge log function name to avoid confusion
  src/libUtils/Logger.h
Labels: Ready

#463 Disable g3log fatal handling temporarily
  cmake/InstallG3log.cmake
Labels: Ready

#365 Enable -Wextra compiler option and other improvements
  CMakeLists.txt
  src/cmd/genkeypair.cpp
  src/common/Broadcastable.h
  src/depends/libDatabase/CMakeLists.txt
  src/depends/libTrie/CMakeLists.txt
  src/libConsensus/ConsensusBackup.cpp
  src/libConsensus/ConsensusBackup.h
  src/libConsensus/ConsensusCommon.h
  src/libConsensus/ConsensusUser.cpp
  src/libData/AccountData/Account.h
  src/libData/BlockChainData/BlockChain.h
  src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
  src/libData/BlockData/BlockHeader/VCBlockHeader.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/PoW2Processing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libDirectoryService/ShardingPostProcessing.cpp
  src/libDirectoryService/ShardingPreProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNetwork/P2PComm.cpp
  src/libNetwork/PeerManager.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/PoWProcessing.cpp
  src/libNode/ShardingInfoProcessing.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libPOW/pow.cpp
  src/libPersistence/ContractStorage.h
  src/libServer/JSONConversion.cpp
  src/libServer/JSONConversion.h
  src/libServer/Server.cpp
  src/libUtils/JsonUtils.h
  src/libUtils/Logger.cpp
  src/libUtils/SafeMath.h
  src/libUtils/SysCommand.h
  src/libUtils/TxnRootComputation.h
  tests/Crypto/CMakeLists.txt
  tests/Crypto/Test_Sha2.cpp
  tests/Crypto/Test_Sha3.cpp
  tests/Data/CMakeLists.txt
  tests/Network/CMakeLists.txt
  tests/POW/CMakeLists.txt
  tests/POW/test_POW.cpp
  tests/Persistence/Test_TrieDB.cpp
  tests/depends/Trie/Test_Trie.cpp
  tests/depends/Trie/Test_TriePerformance.cpp
Labels: Ready, medium

#462 Fix a bug where "consensus done" will be processed more than once
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/ShardingPostProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
Labels: Ready, bug, high

#464 Move sharding serialization code into one place
  src/libDirectoryService/DSBlockMessage.h
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/ShardingPostProcessing.cpp
  src/libDirectoryService/ShardingPreProcessing.cpp
Labels: Ready

#460 Move SetState for POW_SUBMISSION to new epoch
  src/libDirectoryService/FinalBlockPostProcessing.cpp
Labels: Ready, high

#376 Make all blockNum type as uint64_t
  src/libData/BlockChainData/BlockChain.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
  src/libData/BlockData/BlockHeader/MicroBlockHeader.h
  src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.h
  src/libData/DataStructures/CircularArray.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/PoW2Processing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libDirectoryService/ShardingPostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libLookup/Synchronizer.cpp
  src/libLookup/Synchronizer.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoW2Processing.cpp
  src/libNode/PoWProcessing.cpp
  src/libNode/ShardingInfoProcessing.cpp
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libPersistence/Retriever.cpp
  src/libServer/JSONConversion.cpp
  src/libServer/Server.cpp
  src/libServer/Server.h
  tests/Node/test_node_server.sh
  tests/Node/test_node_simple.sh
  tests/Persistence/Test_TxPersistence.cpp
Labels: Ready

#468 Unifying BlockChain.GetLastBlock.GetHeader.GetBlockNum
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/PoW2Processing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libDirectoryService/ShardingPostProcessing.cpp
  src/libDirectoryService/ShardingPreProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/PoWProcessing.cpp
  src/libNode/ShardingInfoProcessing.cpp
  src/libServer/Server.cpp
Labels: Ready, high

#473 Remove redundant InitTemp
  src/libNode/FinalBlockProcessing.cpp
Labels: high

#474 [PoW Merge] Move txn sharing assignments serialization code
  src/libDirectoryService/DSBlockMessage.h
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/ShardingPreProcessing.cpp
Labels: Ready

#476 [PoW Merge] Move sharding deserialization code
  src/libDirectoryService/DSBlockMessage.h
  src/libDirectoryService/ShardingPreProcessing.cpp
Labels: Ready

#475 Rewrite consensus leader/backup checkstate to match node/ds
  src/libConsensus/ConsensusBackup.cpp
  src/libConsensus/ConsensusBackup.h
  src/libConsensus/ConsensusLeader.cpp
  src/libConsensus/ConsensusLeader.h
Labels: Ready, low

#478 [PoW Merge] Move txn sharing assignments deserialization code
  src/libDirectoryService/DSBlockMessage.h
  src/libDirectoryService/ShardingPreProcessing.cpp
  src/libNode/ShardingInfoProcessing.cpp
Labels: Ready

#480 Travis build speed-up and improvement
  .travis.yml
  CMakeLists.txt
  scripts/ci_build.sh
  scripts/ci_report_coverage.sh
Labels: Ready

#479 [PoW Merge] Update SHARDING message sent to Node
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/ShardingPostProcessing.cpp
  src/libNode/Node.h
  src/libNode/ShardingInfoProcessing.cpp
Labels: Ready

#470 Set consensus state to error if there backup has missing txns (at microblock announcement)
  src/libConsensus/ConsensusBackup.cpp
Labels: Ready, bug, high

#486 Increase initial genesis account balance
  src/libNode/Node.cpp
Labels: Ready

#482 [PoW Merge] Remove the max PoW submission limit
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/PoWProcessing.cpp
  src/libLookup/Lookup.cpp
Labels: Ready

#481 Feature/gpu mining
  CMakeLists.txt
  README.md
  constants.xml
  constants_local.xml
  docker/Dockerfile
  scripts/ci_install_deps.sh
  src/common/Constants.cpp
  src/common/Constants.h
  src/depends/CMakeLists.txt
  src/depends/common/CMakeLists.txt
  src/depends/common/Miner.cpp
  src/depends/common/Miner.h
  src/depends/libethash-cl/CL/cl2.hpp
  src/depends/libethash-cl/CLMiner.cpp
  src/depends/libethash-cl/CLMiner.h
  src/depends/libethash-cl/CLMiner_kernel_experimental.cl
  src/depends/libethash-cl/CLMiner_kernel_stable.cl
  src/depends/libethash-cl/CMakeLists.txt
  src/depends/libethash-cl/bin2h.cmake
  src/libPOW/CMakeLists.txt
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  tests/POW/CMakeLists.txt
  tests/POW/test_POW.cpp
Labels: Ready

#485 Put transactions & state delta forwarding after microblockconsensus done
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready
