Repository Zilliqa/Zilliqa, pull requests merged in 2018-11, with the labels that each got.

#780 DS backup verify the PoW winners
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libMediator/Mediator.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libPOW/pow.cpp
  src/libPOW/pow.h
Labels: Ready

#789 Avoid dispatching same messages when gossip is not running
  src/libNetwork/RumorManager.cpp
  src/libNetwork/RumorManager.h
Labels: Ready

#779 Add mbInfoHash in TxBlockHashSet for verification for extra info in TxBlock body
  src/libData/AccountData/Account.cpp
  src/libData/BlockData/BlockHeader/BlockHashSet.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.cpp
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.h
  src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
  src/libData/BlockData/BlockHeader/MicroBlockHeader.h
  src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libLookup/Synchronizer.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  tests/Lookup/Test_LookupNodeForTxBlock.cpp
  tests/Persistence/Test_TxPersistence.cpp
Labels: Ready

#788 Add Epoch Num in DS block
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
  src/libData/BlockData/BlockHeader/MicroBlockHeader.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Synchronizer.cpp
  src/libMediator/Mediator.cpp
  src/libMediator/Mediator.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.h
  src/libNode/ViewChangeBlockProcessing.cpp
  tests/Lookup/Test_LookupNodeForDSBlock.cpp
  tests/Lookup/Test_LookupNodeForTxBlock.cpp
  tests/Node/pre_run.sh
  tests/Persistence/Test_DSPersistence.cpp
Labels: Ready

#791 Use std::equal with internal size check
  src/libMessage/Messenger.cpp
Labels: Ready

#667 Node recovery
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/libDirectoryService/Coinbase.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libPersistence/Retriever.cpp
  src/libPersistence/Retriever.h
  src/libUtils/UpgradeManager.cpp
  src/libZilliqa/Zilliqa.cpp
  tests/Zilliqa/daemon_restart.py
Labels: Ready, enhancement

#799 Fixed incorrect check of AccountStore::DeserializeDelta result
  src/libLookup/Lookup.cpp
  src/libPersistence/Retriever.cpp
Labels: bug

#802 [Hotfix] Disable retrieveHistory for local test
  src/libLookup/Lookup.cpp
  src/libPersistence/BlockStorage.cpp
  tests/Zilliqa/test_zilliqa_archival.py
  tests/Zilliqa/test_zilliqa_local.py
  tests/Zilliqa/test_zilliqa_lookup.py
Labels: Ready, bug

#793 Upgrading mechanism with constant file
  release.sh
  src/libUtils/UpgradeManager.cpp
  src/libUtils/UpgradeManager.h
Labels: Ready, bug

#800 Fix libServer GetBalance bug
  src/libServer/Server.cpp
Labels: Ready, medium

#805 [testnetv4-dev] Upgrading mechanism with constant file
  release.sh
  src/libUtils/UpgradeManager.cpp
  src/libUtils/UpgradeManager.h
Labels: Ready, bug

#796 Get Directory Blocks From Persistence
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libPersistence/Retriever.cpp
  src/libPersistence/Retriever.h
  src/libValidator/Validator.cpp
Labels: Ready

#809 [testnetv4-dev] Added tests in Messenger for consensus
  tests/Message/CMakeLists.txt
  tests/Message/Test_Messenger_Consensus.cpp
  tests/libTestUtils/TestUtils.h
Labels: Ready

#824 [testnetv4-dev] Avoid commit window when NUM_CONSENSUS_SUBSETS=1
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusLeader.cpp
Labels: Ready

#821 [testnetv4-dev] Fix retrieve history failed but genesis account not added to blockchain problem
  src/libData/BlockChainData/BlockLinkChain.h
  src/libLookup/Lookup.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready

#826 Fix node crashed when calculate extra micro block info hash
  src/libMessage/Messenger.cpp
Labels: Ready

#825 [testnetv4-dev] Fix state delta protobuf issue
  src/libData/AccountData/AccountStore.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
Labels: Ready, bug

#823 Fix state delta protobuf issue
  src/libData/AccountData/AccountStore.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
Labels: Ready, bug

#827 Call scilla checker during contract deployment
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#832 Fix Sha2 wrapper Update() when input is empty
  src/libCrypto/Sha2.h
Labels: Ready, bug, enhancement

#830 Fix scilla runner output parsing issue
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#831 [testnetv4-dev] Fix scilla runner output parsing issue
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#829 View change prechecking
  CMakeLists.txt
  build.sh
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
Labels: Ready, enhancement

#838 Remove unsafe function from sendcmd
  src/cmd/sendcmd.cpp
Labels: Ready, enhancement

#751 Combine DSMB to FinalBlock
  CMakeLists.txt
  build.sh
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libConsensus/ConsensusBackup.h
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusCommon.h
  src/libConsensus/ConsensusLeader.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/TxnPool.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libMediator/Mediator.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#839 Trim the num of shard nodes to avoid going beyond COMM_SIZE
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
Labels: Ready

#840 Set NUM_CONSENSUS_SUBSETS to 1 in constants files
  constants.xml
  constants_local.xml
Labels: Ready

#841 Fix contract state delta serialization issue
  src/libMessage/Messenger.cpp
Labels: Ready

#846 Fix lucky draw logic
  src/libDirectoryService/DirectoryService.h
Labels: Ready

#842 Fix potential out-of-bounds in resizing code
  src/libCrypto/Schnorr.cpp
Labels: Ready

#844 Replace unsafe std::equal with the one with size check
  src/libMessage/Messenger.cpp
  src/libNetwork/P2PComm.cpp
  tests/Crypto/Test_Sha2.cpp
  tests/Data/Test_Block.cpp
  tests/Message/Test_Message.cpp
Labels: Ready

#843 protobuf swinfo serialize and deserialize
  src/libMessage/CMakeLists.txt
  src/libMessage/MessengerSWInfo.cpp
  src/libMessage/MessengerSWInfo.h
  src/libMessage/ZilliqaMessage.proto
  src/libUtils/CMakeLists.txt
  src/libUtils/SWInfo.cpp
  src/libUtils/SWInfo.h
Labels: Ready, enhancement

#845 protobuf peer serialize/deserialize
  src/cmd/CMakeLists.txt
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNetwork/CMakeLists.txt
  src/libNetwork/Peer.cpp
  src/libNetwork/Peer.h
Labels: Ready, enhancement

#848 DS rejoin fix.
  src/libDirectoryService/DirectoryService.cpp
  src/libLookup/Lookup.cpp
Labels: Ready

#814 Lookup Rewards (+ Placeholder for Gas Price)
  constants.xml
  constants_local.xml
  src/CMakeLists.txt
  src/common/Constants.cpp
  src/common/Constants.h
  src/libArchival/Archival.cpp
  src/libArchival/Archival.h
  src/libArchival/ArchiveDB.cpp
  src/libArchival/ArchiveDB.h
  src/libArchival/BaseDB.cpp
  src/libArchival/BaseDB.h
  src/libArchival/CMakeLists.txt
  src/libArchival/ExplorerDB.cpp
  src/libArchival/ExplorerDB.h
  src/libDB/CMakeLists.txt
  src/libDirectoryService/Coinbase.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libLookup/CMakeLists.txt
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libLookup/Synchronizer.cpp
  src/libMediator/Mediator.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  src/libZilliqa/CMakeLists.txt
  src/libZilliqa/Zilliqa.cpp
  src/libZilliqa/Zilliqa.h
  tests/POW/test_POW.cpp
Labels: Ready

#849 Migrate recent unit tests from dev branch to master
  src/libMessage/CMakeLists.txt
  src/libMessage/Message.proto
  tests/CMakeLists.txt
  tests/Mediator/CMakeLists.txt
  tests/Mediator/Test_Mediator.cpp
  tests/Mediator/constants.xml
  tests/Message/CMakeLists.txt
  tests/Message/Test_Message.cpp
  tests/Message/Test_Messenger_Consensus.cpp
  tests/Message/Test_Messenger_Primitives.cpp
  tests/RumorSpreading/.gitignore
  tests/RumorSpreading/CMakeLists.txt
  tests/RumorSpreading/Test_RumorSpreading.cpp
  tests/Utils/CMakeLists.txt
  tests/Utils/Test_ShardSizeCalculator.cpp
  tests/libTestUtils/CMakeLists.txt
  tests/libTestUtils/TestUtils.cpp
  tests/libTestUtils/TestUtils.h
Labels: Ready

#857 Remove sendtxn utility
  CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/send_txn.cpp
  tests/Node/test_node_server.sh
  tests/Node/test_node_simple.sh
  tests/Zilliqa/.gitignore
  tests/Zilliqa/test_zilliqa_local.py
Labels: Ready, enhancement

#822 Fix upgrading mechanism issues
  constants.xml
  constants_local.xml
  release.sh
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libUtils/UpgradeManager.cpp
  src/libUtils/UpgradeManager.h
Labels: Ready, bug

#860 LoadShardStructure with retrieve should not do rejoin
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready, bug

#861 Remove the dependency on GENESIS_KEYS
  src/libLookup/Lookup.cpp
Labels: Ready

#864 Rename SWInfo container to prevent the naming confliction for GCC 7.3.0
  src/libMessage/MessengerSWInfo.cpp
  src/libMessage/ZilliqaMessage.proto
  src/libUtils/SWInfo.cpp
  src/libUtils/SWInfo.h
Labels: Ready, bug

#859 Check for nullptr in AccountStoreSC
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready, enhancement

#858 Use log fatal instead of assert in rumourholder.cpp
  src/libRumorSpreading/RumorHolder.cpp
Labels: Ready, enhancement

#865 Avoid using set() when oom occurs in multisig.cpp
  src/libCrypto/MultiSig.cpp
Labels: Ready, bug

#868 Parameterised and tuning the network setting
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
Labels: Ready

#869 Init AccountStore when run Deserialize
  src/libData/AccountData/AccountStore.cpp
Labels: Ready

#871 Add logging for benchmarking
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNetwork/P2PComm.cpp
Labels: Ready

#854 Fix normal node failing PoW and getting stuck.
  src/libLookup/Lookup.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
Labels: Ready

#870 Fix crash when do DS node rejoin
  src/libLookup/Lookup.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libZilliqa/Zilliqa.cpp
Labels: bug

#867 Fix schnorr memory allocation handling
  src/libCrypto/Schnorr.cpp
Labels: Ready

#851 Implementation of Gas Pricer
  constants.xml
  constants_local.xml
  src/cmd/gentxn.cpp
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libDirectoryService/CMakeLists.txt
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/GasPricer.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Synchronizer.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  src/libUtils/SafeMath.h
  src/libValidator/Validator.cpp
  tests/Data/Test_Contract.cpp
  tests/Data/Test_ContractInvoke.cpp
  tests/Data/Test_Transaction.cpp
  tests/Data/Test_TransactionPerformance.cpp
  tests/Lookup/Test_LookupNodeForDSBlock.cpp
  tests/Lookup/Test_LookupNodeForTxBlock.cpp
  tests/Persistence/Test_DSPersistence.cpp
  tests/Utils/Test_RootComputation.cpp
  tests/libTestUtils/TestUtils.cpp
Labels: Ready

#872 Add prev blockHash to DS/VC/FB blocks
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.cpp
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.h
  src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
  src/libData/BlockData/BlockHeader/VCBlockHeader.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/ZilliqaMessage.proto
  src/libNode/FallbackPreProcessing.cpp
  tests/libTestUtils/TestUtils.cpp
Labels: Ready

#874 More mutex for AccountStore against race condition
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libData/AccountData/AccountStoreTrie.h
Labels: Ready

#876 Use reference instead of value to improve efficiency
  src/libLookup/Lookup.cpp
Labels: Ready

#862 Fix daemon cannot re-launch zilliqa process bug
  daemon/ZilliqaDaemon_AWS.cpp
  tests/Zilliqa/daemon_restart.py
Labels: Ready, bug

#856 Improvised gossip using hashes only instead of raw message
  src/libNetwork/RumorManager.cpp
  src/libNetwork/RumorManager.h
  src/libRumorSpreading/Message.cpp
  src/libRumorSpreading/Message.h
  src/libRumorSpreading/RumorHolder.cpp
  src/libRumorSpreading/RumorHolder.h
Labels: Ready

#880 Improve caching in image build
  docker/Dockerfile
  docker/Dockerfile.k8s
  docker/Makefile
Labels: Ready

#879 Add stimulation delay option to stimulate network lag for gossip
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNetwork/RumorManager.cpp
  src/libNode/Node.cpp
Labels: Ready

#882 Refines for DM1/3 test cases
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready

#881 Remove TxBlockHeader::GetNumMicroBlockHashes
  src/libData/BlockData/Block/TxBlock.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.h
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Synchronizer.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/ZilliqaMessage.proto
  src/libNode/FinalBlockProcessing.cpp
  src/libServer/JSONConversion.cpp
  tests/Lookup/Test_LookupNodeForTxBlock.cpp
  tests/Message/Test_Messenger_Primitives.cpp
  tests/Persistence/Test_TxPersistence.cpp
  tests/libTestUtils/TestUtils.cpp
Labels: Ready

#889 [testnetv5-dev] Add partialRetrival flag for RetrieveDSBlocks
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
Labels: Ready

#893 Fix Fetch AccountStates from Lookup
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libLookup/Lookup.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
Labels: Ready

#895 [testnetv5-dev] Wrap operation about m_createdTransaction with mutex in some corner case
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready

#898 [testnetv5-dev] Fix lookup jammed at processing message
  src/libLookup/Lookup.cpp
Labels: Ready

#897 Fix lookup jammed at processing message
  src/libLookup/Lookup.cpp
Labels: Ready

#903 Fix dead lock in AccountStore::Deserialize
  src/libData/AccountData/AccountStore.cpp
Labels: Ready

#896 Wrap operation about m_createdTransaction with mutex in some corner case
  src/libMessage/Messenger.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready

#887 Upgrade ethash library to latest release version 3.0
  CMakeLists.txt
  src/depends/libethash-cl/CLMiner.cpp
  src/depends/libethash-cuda/CUDAMiner.cpp
  src/depends/libethash/CMakeLists.txt
  src/depends/libethash/compiler.h
  src/depends/libethash/data_sizes.h
  src/depends/libethash/endian.h
  src/depends/libethash/ethash.h
  src/depends/libethash/fnv.h
  src/depends/libethash/include/ethash/ethash.h
  src/depends/libethash/include/ethash/ethash.hpp
  src/depends/libethash/include/ethash/hash_types.h
  src/depends/libethash/include/ethash/hash_types.hpp
  src/depends/libethash/include/ethash/keccak.h
  src/depends/libethash/include/ethash/keccak.hpp
  src/depends/libethash/internal.c
  src/depends/libethash/internal.h
  src/depends/libethash/io.c
  src/depends/libethash/io.h
  src/depends/libethash/io_posix.c
  src/depends/libethash/io_win32.c
  src/depends/libethash/lib/ethash/CMakeLists.txt
  src/depends/libethash/lib/ethash/endianness.hpp
  src/depends/libethash/lib/ethash/ethash-internal.hpp
  src/depends/libethash/lib/ethash/ethash.cpp
  src/depends/libethash/lib/ethash/keccak.c
  src/depends/libethash/lib/ethash/keccakf1600.c
  src/depends/libethash/lib/ethash/managed.cpp
  src/depends/libethash/lib/ethash/primes.c
  src/depends/libethash/lib/ethash/primes.h
  src/depends/libethash/mmap.h
  src/depends/libethash/mmap_win32.c
  src/depends/libethash/sha3.c
  src/depends/libethash/sha3.h
  src/depends/libethash/util.c
  src/depends/libethash/util.h
  src/depends/libethash/util_win32.c
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/PoWProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  tests/POW/test_POW.cpp
Labels: Ready

#904 [testnet v5] Fix dead lock in AccountStore::Deserialize
  src/libData/AccountData/AccountStore.cpp
Labels: Ready

#906 Some log cleanup
  src/libPersistence/BlockStorage.cpp
  src/libUtils/Logger.cpp
  src/libUtils/Logger.h
  src/libUtils/ThreadPool.h
Labels: Ready

#907 Fix boost multiprecision int to-string conversion issue
  README.md
  tests/Utils/Test_IPConverter.cpp
Labels: Ready

#905 Minor refactoring and cleaning up for unused variable and so on
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/Node.cpp
  tests/Mediator/constants.xml
Labels: Ready

#911 Suppress build error on macOS Mojave
  tests/Utils/Test_SWInfo.cpp
  tests/libTestUtils/TestUtils.h
Labels: Ready

#915 Reject DSBlock when just started rejoin
  src/libLookup/Lookup.cpp
  src/libNode/DSBlockProcessing.cpp
Labels: Ready

#914 Fix lookup dead loop when node retrieve blocks before bootstrap
  src/libData/BlockChainData/BlockChain.h
  src/libData/BlockData/BlockHeader/BlockHeaderBase.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
  src/libLookup/Lookup.cpp
Labels: Ready

#892 Node recovery on lookup node
  daemon/ZilliqaDaemon_AWS.cpp
  daemon/run.sh
  src/libLookup/Lookup.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPersistence/Retriever.cpp
Labels: Ready

#916 Refactor the function of retriever to improve code style
  src/libNode/Node.cpp
  src/libPersistence/Retriever.cpp
  src/libPersistence/Retriever.h
Labels: Ready

#919 Extend the wait time for DS block
  src/libNode/PoWProcessing.cpp
Labels: Ready

#920 Block PoW DS time out if a DS block is being processing
  src/libData/AccountData/Account.cpp
  src/libNode/PoWProcessing.cpp
  src/libUtils/SafeMath.h
Labels: Ready

#918 Node recovery bug fix
  src/libData/AccountData/AccountStore.cpp
  src/libLookup/Lookup.cpp
Labels: Ready, bug

#926 Don't init full mine context when use GPU to mine
  src/libPOW/pow.cpp
Labels: Ready

#878 Fix DS rejoin.
  src/libData/BlockChainData/BlockChain.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/DSBlockProcessing.cpp
Labels: Ready

#923 Fix Minor Bug May Causing Smart Contract Deployment Failure
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/AccountStoreBase.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.h
Labels: Ready

#929 Use find_package to locate libjson-rpc-cpp
  CMakeLists.txt
  cmake/FindMHD.cmake
  src/libData/AccountData/CMakeLists.txt
  src/libServer/CMakeLists.txt
Labels: Ready

#935 Move timestamp out of BlockHeader into BlockBase. Compute DSBlockHash with concrete vars only
  src/libData/BlockData/Block/BlockBase.cpp
  src/libData/BlockData/Block/BlockBase.h
  src/libData/BlockData/Block/DSBlock.cpp
  src/libData/BlockData/Block/DSBlock.h
  src/libData/BlockData/Block/FallbackBlock.cpp
  src/libData/BlockData/Block/FallbackBlock.h
  src/libData/BlockData/Block/MicroBlock.cpp
  src/libData/BlockData/Block/MicroBlock.h
  src/libData/BlockData/Block/TxBlock.cpp
  src/libData/BlockData/Block/TxBlock.h
  src/libData/BlockData/Block/VCBlock.cpp
  src/libData/BlockData/Block/VCBlock.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.cpp
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.h
  src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
  src/libData/BlockData/BlockHeader/MicroBlockHeader.h
  src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.h
  src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
  src/libData/BlockData/BlockHeader/VCBlockHeader.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Synchronizer.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libProtoServer/Server.cpp
  src/libServer/JSONConversion.cpp
  src/libServer/Server.cpp
  tests/Lookup/Test_LookupNodeForDSBlock.cpp
  tests/Lookup/Test_LookupNodeForTxBlock.cpp
  tests/Persistence/ReadBlock.cpp
  tests/Persistence/ReadTxBlock.cpp
  tests/Persistence/Test_DSPersistence.cpp
  tests/Persistence/Test_TxPersistence.cpp
  tests/libTestUtils/TestUtils.cpp
Labels: Ready

#936 Fix wrong lower case for vc log message
  src/libDirectoryService/DSBlockPreProcessing.cpp
Labels: Ready, enhancement

#930 Spreading POWs as POWPacket with in DS committee
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/libArchival/Archival.cpp
  src/libData/CMakeLists.txt
  src/libData/MiningData/CMakeLists.txt
  src/libData/MiningData/DSPowSolution.cpp
  src/libData/MiningData/DSPowSolution.h
  src/libDirectoryService/CMakeLists.txt
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/PoWProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libMediator/Mediator.cpp
  src/libMessage/CMakeLists.txt
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/Node.cpp
  src/libNode/PoWProcessing.cpp
Labels: Ready

#937 Fix new node failed to rejoin problem
  src/libDirectoryService/DirectoryService.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
Labels: Ready

#941 Initialize the m_isVacuousEpoch flag
  src/libMediator/Mediator.cpp
Labels: Ready

#945 Build option for clang-tidy-fix
  build.sh
Labels: Ready

#942 Change the difficulty adjust algorithm
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  tests/Mediator/constants.xml
  tests/POW/test_POW.cpp
Labels: Ready

#944 Fixed unbalanced transaction dispatching to shards
  src/libData/AccountData/Transaction.cpp
Labels: Ready

#946 Refactor sync type and stop mining if timeout
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/PoWProcessing.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#951 Upgrade mechanism bug fix
  src/libNode/Node.cpp
Labels: Ready, bug

#952 Enable sender thread on every lookup
  src/libLookup/Lookup.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
Labels: Ready

#949 Move out the responsibilty of gossip spreading txn packet from ProcessTxnPacketFromLookupCore
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNetwork/P2PComm.cpp
  src/libNetwork/RumorManager.cpp
  src/libNetwork/RumorManager.h
  src/libNode/Node.cpp
Labels: Ready

#954 Disallow DS to submit PoW
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/PoWProcessing.cpp
Labels: Ready, enhancement

#960 Fix potential crash
  src/libNetwork/RumorManager.cpp
Labels: Ready

#934 [NCC-2018-001] Fix safemath potential issue
  src/libUtils/SafeMath.h
  src/libUtils/SafeMath.tpp
  tests/Utils/Test_SafeMath.cpp
Labels: Ready, bug

#966 Remove SkipDSMicroBlock
  CMakeLists.txt
  build.sh
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready

#964 Refactor the GetBuiltDSComm function
  src/libData/BlockChainData/BlockLinkChain.h
  src/libNode/Node.cpp
  src/libPersistence/Retriever.cpp
Labels: Ready
