Repository Zilliqa/Zilliqa, pull requests merged in 2018-08, with the labels that each got.

#487 [PoW Merge] Move sharding and txn sharing into DSBlock consensus
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/ShardingPostProcessing.cpp
  src/libDirectoryService/ShardingPreProcessing.cpp
Labels: Ready

#498 [PoW Merge] Skip PoW2 phase, plus bug fixes on txn forwarding
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
  src/libNode/ShardingInfoProcessing.cpp
Labels: Ready

#496 Fix log printing and ds block number for microblock
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  tests/Data/Test_Block.cpp
Labels: Ready, bug

#495 Merge m_myShardMembersPubKeys and m_myShardMembersNetworkInfo into one data structure
  src/libNode/Coinbase.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/ShardingInfoProcessing.cpp
Labels: Ready, enhancement

#500 [PoW Merge] Clean up
  constants.xml
  constants_local.xml
  src/cmd/send_txn.cpp
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/libDirectoryService/CMakeLists.txt
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/PoW2Processing.cpp
  src/libDirectoryService/ShardingPostProcessing.cpp
  src/libDirectoryService/ShardingPreProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/CMakeLists.txt
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoW2Processing.cpp
  src/libNode/ShardingInfoProcessing.cpp
Labels: Ready

#502 Add sample and test code for protobuf messaging
  CMakeLists.txt
  README.md
  docker/Dockerfile
  scripts/ci_install_deps.sh
  src/CMakeLists.txt
  src/libMessage/CMakeLists.txt
  src/libMessage/Message.h
  src/libMessage/Message.proto
  tests/CMakeLists.txt
  tests/Message/CMakeLists.txt
  tests/Message/Test_Message.cpp
Labels: Ready, enhancement

#466 Handle and refine view change cornercases
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
Labels: Ready, bug, high

#503 Feature/gpu mining
  CMakeLists.txt
  README.md
  build.sh
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/depends/CMakeLists.txt
  src/depends/common/Miner.h
  src/depends/libethash-cl/CLMiner.cpp
  src/depends/libethash-cuda/CMakeLists.txt
  src/depends/libethash-cuda/CUDAMiner.cpp
  src/depends/libethash-cuda/CUDAMiner.h
  src/depends/libethash-cuda/cuda_helper.h
  src/depends/libethash-cuda/dagger_shuffled.cuh
  src/depends/libethash-cuda/ethash_cuda_miner_kernel.cu
  src/depends/libethash-cuda/ethash_cuda_miner_kernel.h
  src/depends/libethash-cuda/ethash_cuda_miner_kernel_globals.h
  src/depends/libethash-cuda/fnv.cuh
  src/depends/libethash-cuda/keccak.cuh
  src/libPOW/CMakeLists.txt
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  tests/POW/test_POW.cpp
Labels: Ready

#510 Change the calling order of Node::Install() to avoid null pointer dereference issue under recovery mode
  src/libNode/Node.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#507 Updated new node joining after removal of PoW2 phase
  README.md
  src/common/Messages.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libPOW/pow.cpp
Labels: Ready

#505 Use standard libevent procedure
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
Labels: Ready, enhancement

#508 Refine README and other docs
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  img/zilliqa-logo-color.png
Labels: Ready, help wanted

#519 libMessage: suppress unused parameters errors
  src/libMessage/CMakeLists.txt
Labels: Ready

#520 Blacklist support
  src/libNetwork/Blacklist.cpp
  src/libNetwork/Blacklist.h
  src/libNetwork/CMakeLists.txt
  src/libNetwork/P2PComm.cpp
Labels: Ready, enhancement

#521 Blacklist unit test
  tests/Network/CMakeLists.txt
  tests/Network/Test_Blacklist.cpp
Labels: Ready

#527 Add missing header guard
  src/libNetwork/Blacklist.h
  src/libNetwork/Whitelist.h
Labels: Ready, enhancement

#525 Support logging time-stamp on millisecond precision
  src/libUtils/Logger.cpp
  src/libUtils/Logger.h
  src/libUtils/TimeUtils.cpp
  src/libUtils/TimeUtils.h
Labels: Ready, enhancement

#528 Add IP Converter utility
  src/libUtils/CMakeLists.txt
  src/libUtils/IPConverter.cpp
  src/libUtils/IPConverter.h
  tests/Utils/CMakeLists.txt
  tests/Utils/Test_IPConverter.cpp
Labels: Ready, enhancement

#523 Make SafeMath as template
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/AccountStoreBase.tpp
  src/libData/AccountData/AccountStoreSC.tpp
  src/libUtils/SafeMath.h
  tests/Utils/CMakeLists.txt
  tests/Utils/Test_SafeMath.cpp
Labels: Ready, enhancement

#533 Safe math log warning enhancement and comments fix
  src/libUtils/SafeMath.h
Labels: enhancement

#529 [Refactoring] Redesign P2PComm around lock-free message queues
  constants.xml
  constants_local.xml
  src/cmd/main.cpp
  src/cmd/send_txn.cpp
  src/cmd/sendcmd.cpp
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
  src/libZilliqa/Zilliqa.cpp
  src/libZilliqa/Zilliqa.h
  tests/Network/Test_P2PComm.cpp
Labels: Ready

#535 Fix wrong port number in tests
  tests/Node/test_node_simple.sh
  tests/Node/watch_node_simple.sh
Labels: enhancement

#526 Reputation Manager
  src/libNetwork/CMakeLists.txt
  src/libNetwork/ReputationManager.cpp
  src/libNetwork/ReputationManager.h
  tests/Network/CMakeLists.txt
  tests/Network/Test_ReputationManager.cpp
Labels: Ready, enhancement

#540 Automatically adjust PoW difficulty according to PoW submissions
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/PoWProcessing.cpp
Labels: Ready

#543 Fix persistence recovery
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libZilliqa/Zilliqa.cpp
  tests/Node/test_node_simple.sh
Labels: Ready
