Repository Zilliqa/Zilliqa, pull requests merged in 2018-12, with the labels that each got.

#877 Update DS Block & remove placeholders
  src/libServer/JSONConversion.cpp
  src/libServer/Server.cpp
  src/libServer/Server.h
Labels: in-progress

#976 Fix PoW send
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/PoWProcessing.cpp
Labels: Ready

#971 Add Tolerance to txn ordering
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready

#955 Make proof of reputation can work again
  src/libDirectoryService/DSBlockPreProcessing.cpp
Labels: Ready

#981 Fix CUDA and OpenCL link in README
  README.md
Labels: Ready

#985 Add release image build instructions
  docker/Dockerfile
  docker/Dockerfile.cuda
  docker/Makefile
  docker/README.md
Labels: Ready

#968 Recover all nodes at the same time
  src/common/Constants.h
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#988 Ensure that zilliqa/scilla is up-to-date
  docker/Makefile
Labels: enhancement

#953 Implementation of DataSender to send data based on the index in cosignatures
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/TxnPool.h
  src/libData/BlockData/Block/FallbackBlockWShardingStructure.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMessage/Messenger.h
  src/libNetwork/CMakeLists.txt
  src/libNetwork/DataSender.cpp
  src/libNetwork/DataSender.h
  src/libNetwork/ShardStruct.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libUtils/DetachedFunction.h
Labels: Ready

#994 inet_ntop instead of inet_ntoa
  src/libNetwork/Guard.cpp
Labels: enhancement

#992 Fix potential vulnerabilities in ConsensusLeader code
  src/libConsensus/ConsensusLeader.cpp
Labels: Ready

#991 Read IP mapping table after retrieving database
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready, enhancement

#993 Timestamp verification fixing - based on comparison with current local
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libUtils/TimeUtils.cpp
  src/libUtils/TimeUtils.h
  src/libUtils/TimestampVerifier.h
Labels: Ready

#998 Fix lowest 2 bits mask values in DifficultyLevelInInt
  src/libPOW/pow.cpp
Labels: Ready

#999 Make persistence database as thread-safe
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
Labels: Ready, bug

#1002 Check the message size in CanProcessMessage and GetConsensusID
  src/libConsensus/ConsensusCommon.cpp
Labels: Ready

#1000 Add option to disable Fallback
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/FallbackPreProcessing.cpp
Labels: Ready

#1001 Fix potential buffer overflow when using HexStrToStdArray
  src/libDirectoryService/PoWProcessing.cpp
  src/libUtils/DataConversion.cpp
  src/libUtils/DataConversion.h
Labels: Ready

#1004 Fix potential wrong messaging to wrong instruction handler and minor log message fix
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
Labels: Ready, bug

#1006 Initialize all member variables in constructors
  src/libConsensus/ConsensusLeader.cpp
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.cpp
  src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
  src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
  src/libMediator/Mediator.cpp
  src/libRumorSpreading/RumorHolder.cpp
Labels: Ready

#1007 Fix bug for StartRetrieveHistory that may cause state delta check failed
  src/libDirectoryService/Coinbase.cpp
  src/libNode/Node.cpp
Labels: Ready, bug

#989 Log message name to track the size and process time
  CMakeLists.txt
  constants.xml
  constants_local.xml
  src/cmd/CMakeLists.txt
  src/cmd/grepperf.cpp
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/MessageNames.h
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
  src/libNode/FinalBlockProcessing.cpp
  src/libZilliqa/Zilliqa.cpp
  src/libZilliqa/Zilliqa.h
  tests/Message/CMakeLists.txt
  tests/Message/Test_MessageName.cpp
Labels: Ready

#1011 Avoid printing private key information in the log file
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1010 Check for null oriAccount before dereferencing
  src/libMessage/Messenger.cpp
Labels: Ready

#1008 Always buffer txns from lookup and only do gossip during txn distribution
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#1016 Support ISO 8601 for log timestamp
  src/libUtils/Logger.cpp
  src/libUtils/Logger.h
Labels: Ready

#1003 Merging sending of mb and forward txn to lookup with DataSender
  src/common/MessageNames.h
  src/common/Messages.h
  src/libData/AccountData/MBnForwardedTxnEntry.h
  src/libData/AccountData/TransactionReceipt.h
  src/libData/AccountData/TxnOrderVerifier.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNetwork/DataSender.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#1020 Fix crash of calling IsLookupNode
  src/libLookup/Lookup.cpp
Labels: Ready

#1009 Develop the script to profile consensus time from state log
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  tests/Zilliqa/profile_time.py
Labels: Ready

#1021 fix 100% CPU problem
  src/libNetwork/P2PComm.cpp
Labels: Ready

#1019 Remove TxSharingAssignment
  src/libData/BlockData/BlockHeader/BlockHashSet.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.h
  tests/Message/Test_Messenger_Primitives.cpp
Labels: Ready

#986 Adjust DS Block wait time for shard node after PoW submission
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/PoWProcessing.cpp
Labels: Ready

#1013 Refactor the get DS leader peer into a function
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libMediator/Mediator.h
  src/libNetwork/ShardStruct.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
Labels: Ready

#1026 Fix node rejoin and win DS PoW and then process sharding structure fail
  src/libDirectoryService/DirectoryService.h
  src/libNode/Node.cpp
Labels: Ready

#1018 New lookup join the n/w with latest blocks and states
  src/common/Constants.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1028 Node start to rejoin if missed some tx blocks
  src/libMediator/Mediator.cpp
  src/libNode/FinalBlockProcessing.cpp
Labels: Ready

#1030 Remove unnecessary cv usage from ThreadPool
  src/libUtils/ThreadPool.h
Labels: Ready

#1031 State log for txn distribution & Log for benchmark on contract transaction
  src/libData/AccountData/AccountStoreSC.tpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#1029 Refactor FinishRejoinAsDS function to use GetDSLeaderPeer
  src/libDirectoryService/DirectoryService.cpp
  src/libNode/Node.cpp
Labels: Ready

#1032 Avoid unnecessary errorMsg generation for some calls to CheckMicroBlocks
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
Labels: Ready

#1037 Change the log of job pool from 10 to 100
  src/libUtils/ThreadPool.h
Labels: Ready

#1039 Fix SafeMath potential bug and apply on broadcast message
  src/libNetwork/P2PComm.cpp
  src/libUtils/SafeMath.h
  src/libUtils/SafeMath.tpp
  tests/Utils/Test_SafeMath.cpp
Labels: Ready, bug

#1044 Add signature validation to PeerManager Hello message
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNetwork/PeerManager.cpp
  tests/Zilliqa/test_zilliqa_NAT.py
  tests/Zilliqa/test_zilliqa_archival.py
  tests/Zilliqa/test_zilliqa_late.py
  tests/Zilliqa/test_zilliqa_local.py
  tests/Zilliqa/test_zilliqa_lookup.py
Labels: Ready

#1042 Fix select GPU index other than 0 software crash problem
  src/depends/libethash-cuda/CUDAMiner.cpp
  src/libPOW/pow.cpp
Labels: Ready, bug

#1040 Removed getTransactionHistory and getCode from JSON spec
  src/libServer/spec.json
Labels: Ready

#1027 Refactor ParseContractOutput
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#1046 Fix the deadlock on mutex m_mutexLookupNodes + Delay starting new lookup syncup
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libLookup/Lookup.cpp
Labels: Ready

#1049 Apply delay for lookup sending txn for every epoch
  constants_local.xml
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready

#1047 Simplify log level output
  src/libUtils/Logger.cpp
Labels: Ready

#1053 Removed unnecessary check from div_signint
  src/libUtils/SafeMath.tpp
Labels: Ready

#938 LookupArchival to send txns to Lookups
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libServer/Server.cpp
  src/libServer/Server.h
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1048 Change COINBASE_REWARD reading from constants to uint128_t
  src/common/Constants.cpp
  src/common/Constants.h
Labels: Ready

#1051 Enhance state log and enhance script to fetch information from it
  src/libDirectoryService/Coinbase.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  tests/Zilliqa/profile_time.py
Labels: Ready

#1055 Fix DS nodes not sending DS microblock to Lookups
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNetwork/DataSender.cpp
Labels: Ready

#996 Bytes size check for tx hash
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  tests/Message/Test_Messenger_Primitives.cpp
Labels: Ready, enhancement

#1060 Revised microsec_timestamp_to_readable
  constants.xml
  constants_local.xml
  src/libUtils/TimeUtils.cpp
Labels: Ready

#1063 Validate the ConsensusFailure message from the Leader
  src/libConsensus/ConsensusBackup.cpp
  src/libConsensus/ConsensusLeader.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  tests/Message/Test_Messenger_Consensus.cpp
Labels: Ready

#1062 Cast uint128_t to int256_t when trying to get negative value
  src/libMessage/Messenger.cpp
Labels: Ready

#1064 New lookp-up to support forwarding txn to above layer
  src/libLookup/Lookup.cpp
  src/libServer/Server.cpp
Labels: Ready

#1067 Add tolerance to different ip address in processing sharding structure
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/TxnOrderVerifier.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  tests/Data/Test_TxnOrder.cpp
  tests/Zilliqa/profile_time.py
Labels: Ready

#1071 re-enable ds persistence unit test
  tests/Persistence/Test_DSPersistence.cpp
Labels: enhancement

#1072 UpdateStateTrieAll after adding genesis account
  src/libNode/Node.cpp
Labels: Ready, bug

#1066 Add constants field for easier setting of min gas price
  constants.xml
  constants_local.xml
  src/cmd/gentxn.cpp
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/AccountStore.cpp
  src/libDirectoryService/GasPricer.cpp
  src/libMessage/Messenger.cpp
  src/libNode/Node.cpp
Labels: Ready

#1074 Fix potential concurrency issue when running view change
  src/libDirectoryService/ViewChangePreProcessing.cpp
Labels: Ready, bug

#1022 Bug fix for entire testnet recovery
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libLookup/Lookup.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
  src/libPersistence/Retriever.cpp
  src/libPersistence/Retriever.h
  src/libZilliqa/Zilliqa.cpp
Labels: Ready, bug

#1057 DS Committee network information update and other various fixes
  CMakeLists.txt
  constants.xml
  constants_local.xml
  src/cmd/main.cpp
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/libConsensus/ConsensusUser.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMediator/Mediator.cpp
  src/libMediator/Mediator.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNetwork/Guard.cpp
  src/libNetwork/Guard.h
  src/libNetwork/PeerManager.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
  src/libZilliqa/Zilliqa.cpp
  tests/Node/test_node_rejoindsguardnode2.sh
  tests/Zilliqa/test_zilliqa_local.py
Labels: Ready

#1073 Add missing check for NullAddress for normal txn
  src/libServer/Server.cpp
Labels: Ready

#1078 Moved POWPACKETSUBMISSION_WINDOW_IN_SECONDS from data_sharing to epoch_timing
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
Labels: Ready

#1076 Changed Protobuf definitions to allow backward compatibility in persistent storage
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  tests/Message/CMakeLists.txt
  tests/Message/Test_Messenger_Compatibility.cpp
  tests/Message/ZilliqaTest.proto
Labels: Ready

#1075 Add checking of difficulty in DSBlock before processing/verifying transaction
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready

#1081 Check txn from late epoch with tolerance
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/TxnOrderVerifier.h
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#1085 Check gas price when receiving rpc request as lookup
  src/libLookup/Lookup.cpp
  src/libServer/Server.cpp
Labels: Ready

#1086 Move profile_time.py to scripts folder
  scripts/profile_time.py
Labels: Ready

#1083 An offline tool to verify back-up database integrity
  constants.xml
  constants_local.xml
  scripts/validateBackupDB.sh
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/Node.cpp
  tests/Node/test_node_validateBackupDB.py
  tests/Zilliqa/test_zilliqa_local.py
Labels: Ready, enhancement

#1088 Clean TxnPacketBuffer after committing
  constants.xml
  src/libNode/Node.cpp
Labels: Ready

#1089 Fix potential race condition in CommitMicroBlockConsensusBuffer
  src/libNode/MicroBlockPostProcessing.cpp
Labels: bug, in-progress

#1092 CommitTxnPacketBuffer after InitializeRumorManager
  src/libNode/DSBlockProcessing.cpp
Labels: bug

#1091 Fix DS Forwarding Processed Transaction Too Early
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
Labels: Ready

#1096 Remove Rsync used in Lookup
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
Labels: Ready

#1098 Add tolerance to sharding algorithm
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libUtils/ShardSizeCalculator.cpp
  src/libUtils/ShardSizeCalculator.h
  tests/Utils/Test_ShardSizeCalculator.cpp
Labels: Ready

#1100 Fix extra StateDelta being retrieved if TxBlock from DB is inconsistent
  src/libData/BlockChainData/BlockChain.h
  src/libData/DataStructures/CircularArray.h
  src/libDirectoryService/Coinbase.cpp
  src/libDirectoryService/DirectoryService.h
  src/libNode/Node.cpp
  src/libPersistence/Retriever.cpp
Labels: Ready

#1109 Refine the reward log to easy understand
  src/libDirectoryService/Coinbase.cpp
  src/libNode/FinalBlockProcessing.cpp
Labels: Ready

#1097 Modification of hash functions for MultiSig
  src/common/Constants.h
  src/libConsensus/ConsensusBackup.cpp
  src/libConsensus/ConsensusLeader.cpp
  src/libCrypto/MultiSig.cpp
  src/libCrypto/MultiSig.h
  src/libCrypto/Schnorr.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libValidator/Validator.cpp
  tests/Crypto/Test_MultiSig.cpp
  tests/Message/Test_Messenger_Consensus.cpp
Labels: Ready

#1101 P2PCom set upper size limit on incoming gossip message
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNetwork/P2PComm.cpp
  src/libNetwork/RumorManager.cpp
Labels: Ready

#1113 Unify the type for consensusMyID and consensusLeaderID
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.cpp
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libMessage/ZilliqaMessage.proto
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#1118 Periodic cleanup of gossip raw message store
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNetwork/RumorManager.cpp
  src/libNetwork/RumorManager.h
Labels: Ready

#1114 DS difficulty mining start with shard difficulty winning nonce
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libMessage/Messenger.h
  src/libNode/Node.cpp
  src/libNode/PoWProcessing.cpp
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  tests/POW/test_POW.cpp
Labels: Ready

#1115 Add EpochNum in TxnReceipt
  src/libData/AccountData/TransactionReceipt.cpp
  src/libData/AccountData/TransactionReceipt.h
  src/libValidator/Validator.cpp
Labels: Ready

#1120 Separate SHARD_SIZE_THRESHOLD into low and high values
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libUtils/ShardSizeCalculator.cpp
  src/libUtils/ShardSizeCalculator.h
  tests/Utils/Test_ShardSizeCalculator.cpp
Labels: Ready

#1112 Feature/diagnosticdb
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  tests/Persistence/CMakeLists.txt
  tests/Persistence/Test_Diagnostic.cpp
  tests/libTestUtils/TestUtils.cpp
Labels: Ready

#1108 Decide receiver of DataSender based on CoSigs
  src/libData/BlockData/Block/BlockBase.cpp
  src/libData/BlockData/Block/BlockBase.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNetwork/DataSender.cpp
  src/libNetwork/DataSender.h
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready

#1121 Use NullAddr to issue coinbase rewards and forbid txn sent from it
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/Coinbase.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libServer/Server.cpp
  src/libValidator/Validator.cpp
Labels: Ready

#1127 Updated diagnostic data retrieval
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  tests/Persistence/Test_Diagnostic.cpp
Labels: Ready

#1123 Base reward for all nodes in the network (shard & DS)
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/Coinbase.cpp
Labels: Ready

#1129 Init RumorManager with empty peers in Node::CleanVariables
  src/libNode/Node.cpp
Labels: Ready
