Repository Zilliqa/Zilliqa, pull requests merged in 2019-02, with the labels that each got.

#1369 Update README for mainnet
  README.md
Labels: low

#1387 Fixed misleading log message for vacuous epoch
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready

#1388 Remove broadcast list from PeerManager
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNetwork/PeerManager.cpp
Labels: Ready

#1389 Stop mining if mining time over POW_WINDOW_IN_SECONDS
  constants.xml
  src/libPOW/pow.cpp
  tests/POW/test_POW.cpp
Labels: Ready

#1392 Fix total gas used check fail problem
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.h
Labels: Ready

#1394 Fix rejoined DS backup using the wrong vacuous epoch flag
  src/libLookup/Lookup.cpp
Labels: Ready

#1395 Fix a rare cornercase in view change
  src/libDirectoryService/ViewChangePreProcessing.cpp
Labels: Ready, bug, enhancement

#1398 Daemon should not launch process with --loadconfig
  tests/Zilliqa/daemon_restart.py
Labels: Ready

#1399 Revert PR 1392 except for init in constructor
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready

#1391 Add security bug bounty and explorer 2 link
  README.md
Labels: Ready

#1397 To tag v4.0.2
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1412 Log the zilliqa brand and version in log file
  src/cmd/main.cpp
  src/libUtils/SWInfo.h
Labels: Ready, enhancement

#1414 Add asan and tsan to make image script
  CMakeLists.txt
  scripts/make_image_for_test.sh
Labels: Ready, enhancement

#1417 Update readme
  README.md
Labels: Ready, enhancement

#1404 Do coinbase again when VC happens
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
Labels: Ready

#1419 Removed unused code in Lookup
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libLookup/Synchronizer.cpp
  src/libLookup/Synchronizer.h
Labels: Ready

#1426 Shifting ProcessTxn before receiving announcement for backup node
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libMediator/Mediator.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.h
Labels: Ready

#1422 Check if user using latest sw version to join mainnet
  src/cmd/main.cpp
  src/common/Constants.h
  src/libUtils/SWInfo.cpp
  src/libUtils/SWInfo.h
  tests/Utils/Test_SWInfo.cpp
Labels: Ready

#1423 Add new_ds_guard in constant file
  constants.xml
  constants_local.xml
Labels: Ready

#1393 Use nonblocking socket for handling connection issue
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNetwork/P2PComm.cpp
Labels: Ready

#1421 Skip Runner When Checker Failed And Adjust Gas Penalty For Contract Deployment
  constants.xml
  constants_local.xml
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#1418 Avoid massive memory consumption during state retrieval
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStoreTrie.h
  src/libData/AccountData/AccountStoreTrie.tpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libPersistence/Retriever.cpp
Labels: Ready

#1429 Add DM9 vc test and minor modification on previous dm tests
  CMakeLists.txt
  build.sh
  scripts/make_image_for_test.sh
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready

#1435 Revert "Add new_ds_guard in constant file"
  constants.xml
  constants_local.xml
Labels: Ready

#1433 Two-subset consensus
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libConsensus/ConsensusBackup.cpp
  src/libConsensus/ConsensusBackup.h
  src/libConsensus/ConsensusCommon.h
  src/libConsensus/ConsensusLeader.cpp
  src/libConsensus/ConsensusLeader.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/MicroBlockPreProcessing.cpp
  tests/Message/Test_Messenger_Consensus.cpp
Labels: Ready

#1436 Use a non class variable when in DS consensus is not finalized
  src/libDirectoryService/DSBlockPreProcessing.cpp
Labels: bug

#1432 Display missing responses before view change
  src/libConsensus/ConsensusLeader.cpp
  src/libConsensus/ConsensusLeader.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
Labels: Ready

#1441 Remove expired log
  src/libData/AccountData/AccountStoreTrie.tpp
Labels: Ready

#1442 Recovery sequence should be controlled by script instead of C++ code.
  constants.xml
  constants_local.xml
Labels: Ready

#1444 Buffer and Process received final blocks after seed is syncedup
  CMakeLists.txt
  build.sh
  scripts/make_image_for_test.sh
  src/libLookup/Lookup.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#1450 Update readme current live version 4.0.2 -> 4.1.0
  README.md
Labels: Ready, enhancement

#1457 [Release-4.1] Delete object before returning
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1454 [Release-4.1] Handle gossip foreign message properly
  src/libNetwork/RumorManager.cpp
Labels: Ready

#1459 [Release-4.1] Minor fix on consensus check
  src/libData/AccountData/AccountStoreTrie.tpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
Labels: Ready

#1455 Delete object before returning
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1453 Handle gossip foreign message properly
  src/libNetwork/RumorManager.cpp
Labels: Ready

#1458 Minor fix on consensus check
  src/libDirectoryService/FinalBlockPostProcessing.cpp
Labels: Ready

#1461 Revert non blocking socket PR
  src/libNetwork/P2PComm.cpp
Labels: Ready

#1466 [release-4.1] Update version to v4.1.1
  README.md
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1469 [release-4.1] Set vacuous epoch during recovery
  src/libNode/Node.cpp
Labels: Ready, bug

#1468 Set vacuous epoch during recovery
  src/libNode/Node.cpp
Labels: bug

#1467 Update master branch readme current live version 4.1.0 -> 4.1.1
  README.md
Labels: Ready

#1462 Newly joined Seed don't have sharding structure until recv VCDSBlockMessage
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
Labels: Ready

#1456 Put Epoch/Difficulty checker for txn processing
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready

#1471 Check the pow submitter address and submitted count
  src/libDirectoryService/PoWProcessing.cpp
Labels: Ready

#1476 Check result of IncreaseNonce
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/AccountStoreBase.tpp
  src/libData/AccountData/AccountStoreSC.tpp
  src/libMessage/Messenger.cpp
  tests/Data/Test_Account.cpp
  tests/Data/Test_AccountStore.cpp
Labels: Ready

#1478 Release script for rolling upgrading
  scripts/release.sh
Labels: Ready

#1480 Fix typo
  scripts/release.sh
Labels: Ready

#1447 Add Checks for return from IncreaseBalance
  src/libData/AccountData/AccountStoreBase.tpp
  src/libData/AccountData/AccountStoreSC.tpp
  src/libDirectoryService/Coinbase.cpp
Labels: Ready

#1484 Don't exit software if not latest version
  src/cmd/main.cpp
  src/libUtils/SWInfo.cpp
Labels: Ready

#1449 Adjust the order for checking _accepted in scilla output
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#1482 Fix m_syncType may have data race issue
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
Labels: Ready

#1443 Fix the code for setting a lookup back online
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1481 Fix sometimes travis auto build fail problem
  tests/POW/test_POW.cpp
Labels: Ready

#1487 Add epoch number to state log
  src/libMediator/Mediator.cpp
Labels: Ready

#1439 Fix DS pow time window not accurate problem
  src/libNode/PoWProcessing.cpp
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  src/libServer/GetWorkServer.cpp
  src/libServer/GetWorkServer.h
  tests/POW/test_POW.cpp
  tests/POW/test_RemoteMine.cpp
Labels: Ready

#1477 Add check for offset overflow in BIGNUMSerialize
  src/libCrypto/BIGNUMSerialize.cpp
Labels: Ready

#1488 Lookup node should store ds leader information into persistance
  src/libNode/DSBlockProcessing.cpp
Labels: Ready, bug

#1490 Improve gossip
  src/libNetwork/RumorManager.cpp
Labels: Ready

#1479 Add exception checking inside convertStrtoJson
  src/libData/AccountData/TransactionReceipt.cpp
  src/libUtils/JsonUtils.h
Labels: Ready

#1486 Add state check before entering WhenDone funcs for all consensus
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
Labels: Ready, bug

#1489 Improve messaging
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
Labels: Ready

#1483 Test_AccountStore with Contract and Minor Fixing on AccountStore
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/Account.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/AccountStoreTrie.tpp
  src/libMessage/Messenger.cpp
  src/libMessage/MessengerAccountStoreTrie.cpp
  src/libMessage/MessengerAccountStoreTrie.h
  src/libServer/Server.cpp
  tests/Data/AccountData/CMakeLists.txt
  tests/Data/AccountData/Test_Account.cpp
  tests/Data/AccountData/Test_AccountStore.cpp
Labels: Ready

#1485 Modify COMMIT_TOLERANCE_PERCENT
  constants.xml
  constants_local.xml
Labels: Ready

#1491 Add more check MAX_CODE_SIZE_IN_BYTES
  src/libServer/Server.cpp
  src/libValidator/Validator.cpp
Labels: Ready

#1493 Fix break on view change after the change for fixing consensus race condition
  src/libDirectoryService/FinalBlockPreProcessing.cpp
Labels: Ready

#1496 Check IP of commit/response message
  src/libConsensus/ConsensusLeader.cpp
  src/libConsensus/ConsensusLeader.h
Labels: Ready

#1495 Use multicast for UpdateDSGuardIdentity
  src/libDirectoryService/DirectoryService.cpp
Labels: Ready

#1498 Fix AccountStore Lock in MacOS
  src/libData/AccountData/AccountStore.cpp
Labels: Ready

#1494 Adjust blacklist exclusion list
  constants_local.xml
  src/libDirectoryService/DirectoryService.cpp
  src/libLookup/Lookup.cpp
  src/libNetwork/Blacklist.cpp
  src/libNetwork/Blacklist.h
  src/libNetwork/Guard.cpp
  src/libNetwork/Guard.h
  src/libNode/Node.cpp
  src/libNode/PoWProcessing.cpp
Labels: Ready, enhancement
