Repository Zilliqa/Zilliqa, pull requests merged in 2019-05, with the labels that each got.

#1632 Fix check scilla output fail problem
  src/libData/AccountData/AccountStoreSC.tpp
  tests/Data/Test_Contract.cpp
Labels: Ready

#1634 skip set online for newlookup
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
Labels: Ready, bug

#1633 Persistence Validation Script
  CMakeLists.txt
  scripts/validatePersistence.sh
  src/cmd/CMakeLists.txt
  src/cmd/validateDB.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#1623 Refactor GetTransactionType
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/Transaction.h
  src/libProtoServer/Server.cpp
  src/libServer/LookupServer.cpp
  src/libServer/Server.cpp
  src/libServer/Server.h
  src/libValidator/Validator.cpp
Labels: Ready

#1628 Consolidate shard calculation
  src/libData/AccountData/Transaction.cpp
  src/libData/AccountData/Transaction.h
  src/libLookup/Lookup.cpp
  src/libServer/LookupServer.cpp
  src/libValidator/Validator.cpp
  tests/Lookup/Test_txn_send.cpp
Labels: Ready

#1640 Fix typo for POW::CheckDifficulty()
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  tests/POW/test_POW.cpp
Labels: Ready

#1646 [release-4.6] To V4.6.1
  CMakeLists.txt
  README.md
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  scripts/validatePersistence.sh
  src/cmd/CMakeLists.txt
  src/cmd/validateDB.cpp
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/Transaction.cpp
  src/libData/AccountData/Transaction.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  src/libProtoServer/Server.cpp
  src/libServer/LookupServer.cpp
  src/libServer/Server.cpp
  src/libServer/Server.h
  src/libUtils/SWInfo.h
  src/libValidator/Validator.cpp
  tests/Lookup/Test_txn_send.cpp
  tests/POW/test_POW.cpp
Labels: Ready

#1647 Use Travis native Ubuntu 16.04
  .travis.yml
  scripts/ci_install_deps.sh
Labels: Ready

#1649 [release-4.5] To V4.5.1
  README.md
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libUtils/SWInfo.h
  src/libZilliqa/Zilliqa.cpp
  tests/POW/test_POW.cpp
Labels: Ready

#1631 Daemon support for community seed
  daemon/CMakeLists.txt
  daemon/ZilliqaDaemon_AWS.cpp
  daemon/run.sh
Labels: Ready

#1641 Properer handling for failures of BlockStorage
  src/depends/libDatabase/OverlayDB.cpp
  src/depends/libDatabase/OverlayDB.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/BlockChainData/BlockLinkChain.cpp
  src/libData/BlockChainData/BlockLinkChain.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Synchronizer.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPersistence/Retriever.cpp
  src/libValidator/Validator.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1642 Add exhaustive test for SafeMath
  src/common/Constants.cpp
  src/libUtils/SafeMath.h
  src/libUtils/SafeMath.tpp
  tests/Utils/CMakeLists.txt
  tests/Utils/Test_SafeMath_Exhaustive.cpp
Labels: Ready

#1655 Protect destructors of some template classes
  src/libData/BlockChainData/BlockChain.h
  src/libServer/Server.h
Labels: Ready

#1638 Fix remap for contract call txns
  src/libLookup/Lookup.cpp
  tests/Lookup/Test_txn_send.cpp
  tests/libTestUtils/TestUtils.cpp
  tests/libTestUtils/TestUtils.h
Labels: Ready

#1659 Add pedantic flag to compiler options
  CMakeLists.txt
  src/libData/BlockChainData/BlockLinkChain.cpp
  src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
  src/libServer/LookupServer.cpp
  src/libServer/LookupServer.h
  src/libServer/Server.cpp
  src/libUtils/Logger.cpp
  src/libUtils/RootComputation.cpp
  src/libUtils/SWInfo.cpp
  tests/Data/Test_EIP.cpp
  tests/POW/test_POW.cpp
  tests/Utils/Test_SafeMath_Exhaustive.cpp
Labels: Ready

#1662 Increase max peer connection
  constants.xml
  constants_local.xml
Labels: Ready

#1663 Handle peer connection counter correctly
  src/libNetwork/P2PComm.cpp
Labels: Ready

#1658 Handle connection timeout
  src/libNetwork/P2PComm.cpp
Labels: Ready

#1652 Fix issues reported by cppcheck
  daemon/ZilliqaDaemon_AWS.cpp
  src/libConsensus/ConsensusCommon.cpp
  src/libData/AccountData/Transaction.cpp
  src/libData/AccountData/Transaction.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libNetwork/P2PComm.cpp
  src/libPersistence/ContractStorage.cpp
  src/libPersistence/Retriever.cpp
  tests/Data/BlockChainData/Test_BlockChain.cpp
  tests/Data/Test_Block.cpp
  tests/cmd/verifyMultiSignature.cpp
Labels: Ready, enhancement

#1556 Pregen Accounts In Batch and Toggle Pregened Accounts Updating
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#1656 Use EPOCHFIN to replace redundant recovery related conditions
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStoreTrie.h
  src/libData/AccountData/AccountStoreTrie.tpp
  src/libData/AccountData/Transaction.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libPersistence/Retriever.cpp
  src/libServer/StatusServer.cpp
  src/libServer/StatusServer.h
Labels: Ready

#1667 Add blockhash to tx block JSON
  src/libServer/JSONConversion.cpp
Labels: Ready

#1670 Add SECURITY.MD
  SECURITY.md
Labels: Ready

#1660 Fix some uninitialized params & Remove explicit copy constructor for std::move
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/Transaction.cpp
  src/libData/AccountData/Transaction.h
  src/libData/BlockData/Block/BlockBase.h
Labels: Ready

#1672 Custom storage path
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/depends/libDatabase/LevelDB.cpp
  src/libLookup/Lookup.cpp
  src/libNode/Node.cpp
  src/libPersistence/Retriever.cpp
Labels: Ready, enhancement

#1669 [Release 4.6] Custom storage path
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/depends/libDatabase/LevelDB.cpp
  src/libLookup/Lookup.cpp
  src/libNode/Node.cpp
  src/libPersistence/Retriever.cpp
Labels: Ready, enhancement

#1678 [release-4.6] To v4.6.2
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1679 Fetch constant file from dsguard instead of normal node
  scripts/release.sh
Labels: Ready, bug
