Repository Zilliqa/Zilliqa, pull requests merged in 2019-03, with the labels that each got.

#1499 To v4.2.0
  README.md
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1506 Initialize SyncType when constructing Lookup
  src/cmd/main.cpp
  src/common/Constants.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libZilliqa/Zilliqa.cpp
  src/libZilliqa/Zilliqa.h
Labels: Ready

#1502 Updates for backward-compatible development
  .github/PULL_REQUEST_TEMPLATE.md
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
Labels: Ready

#1508 Adjustment to shard guards
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
Labels: Ready, enhancement

#1507 Coinbase component test
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  tests/CMakeLists.txt
  tests/Incentives/CMakeLists.txt
  tests/Incentives/test_coinbase.cpp
  tests/libTestUtils/TestUtils.cpp
  tests/libTestUtils/TestUtils.h
Labels: Ready

#1497 Avoid excessive key searches in coinbase rewarding algorithm
  src/libDirectoryService/Coinbase.cpp
Labels: Ready

#1510 Re-serialize consensus msg when buffering
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusCommon.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libMessage/Messenger.h
  src/libNode/MicroBlockPostProcessing.cpp
Labels: Ready

#1511 Remove old upgrading code
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libMediator/Mediator.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libUtils/UpgradeManager.cpp
  src/libUtils/UpgradeManager.h
Labels: Ready

#1513 Adjust and refactor of code for shard operation
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libLookup/Lookup.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready, enhancement

#1518 Refactor and fix calculate shard leader
  src/libLookup/Lookup.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready, bug, enhancement

#1522 Force multicast to shard guards after upgrading
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libNetwork/DataSender.cpp
  src/libNetwork/DataSender.h
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready

#1526 Only set m_forceMulticast to true for DS node
  src/libNode/Node.cpp
Labels: Ready

#1527 To v4.3.0
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1529 Update README to v4.3.0
  README.md
Labels: Ready

#1528 Remove old upgrading mechanism
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#1520 Don't increase difficulty at 1 year epoch number
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  tests/POW/test_POW.cpp
Labels: Ready

#1521 m_receivedRaiseStartPoW may have data race issue
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
Labels: Ready

#1532 Print ds leader ID in state file
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
Labels: Ready

#1525 Fix pow window time for node not correct
  src/libNode/PoWProcessing.cpp
Labels: Ready

#1535 [release-4.3] To v4.3.1
  README.md
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1536 Remove verification of time stamp when node is processing vcblock
  src/libNode/ViewChangeBlockProcessing.cpp
Labels: Ready, bug

#1539 To v4.3.1 for readme
  README.md
Labels: Ready

#1537 Fix DS backup cannot find pow in sorted solutions
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/PoWProcessing.cpp
Labels: Ready

#1501 Repopulate Merkle Trie When MoveUpdatesToAccountStore
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libData/AccountData/AccountStoreTrie.h
  src/libData/AccountData/AccountStoreTrie.tpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.h
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  tests/Data/AccountData/Test_AccountStore.cpp
Labels: Ready

#1541 Verify pow solution before buffer it
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/PoWProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready

#1544 Increase protobuf limit for some Get messages
  src/libMessage/Messenger.cpp
  tests/Message/CMakeLists.txt
  tests/Message/Test_Messenger_Limits.cpp
Labels: Ready

#1547 Don't detach thread when MoveUpdatesToDisk
  constants.xml
  constants_local.xml
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
Labels: Ready, enhancement

#1550 ZilliqaDaemon exits immediately at startup if no zilliqa process is yet launched
  daemon/ZilliqaDaemon.cpp
  daemon/ZilliqaDaemon_AWS.cpp
Labels: Ready

#1540 Rejoining as Normal/DS from S3
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/depends/libDatabase/LevelDB.cpp
  src/depends/libDatabase/LevelDB.h
  src/libDirectoryService/DirectoryService.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libPersistence/Retriever.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1551 Rejoin As Normal/DS from S3
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/depends/libDatabase/LevelDB.cpp
  src/depends/libDatabase/LevelDB.h
  src/libDirectoryService/DirectoryService.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libPersistence/Retriever.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1549 Add option to run test with pre-generated accounts
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#1543 [POW] Divided difficulty adjustment
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  src/libUtils/DataConversion.h
  tests/POW/test_POW.cpp
  tests/POW/test_RemoteMine.cpp
Labels: Ready

#1552 Add status RPC
  .travis.yml
  CMakeLists.txt
  cmake/InstallJsonrpccpp.cmake
  constants.xml
  constants_local.xml
  scripts/miner_info.py
  src/common/Constants.cpp
  src/common/Constants.h
  src/depends/CMakeLists.txt
  src/depends/safeserver/CMakeLists.txt
  src/depends/safeserver/LICENSE.txt
  src/depends/safeserver/safehttpserver.cpp
  src/depends/safeserver/safehttpserver.h
  src/depends/safeserver/safelinuxtcpsocketserver.cpp
  src/depends/safeserver/safelinuxtcpsocketserver.h
  src/depends/safeserver/safetcpsocketserver.cpp
  src/depends/safeserver/safetcpsocketserver.h
  src/libDirectoryService/DirectoryService.h
  src/libLookup/CMakeLists.txt
  src/libNode/Node.h
  src/libPOW/CMakeLists.txt
  src/libPOW/pow.h
  src/libServer/CMakeLists.txt
  src/libServer/GetWorkServer.cpp
  src/libServer/GetWorkServer.h
  src/libServer/JSONConversion.cpp
  src/libServer/JSONConversion.h
  src/libServer/Server.cpp
  src/libServer/Server.h
  src/libZilliqa/CMakeLists.txt
  src/libZilliqa/Zilliqa.cpp
  src/libZilliqa/Zilliqa.h
Labels: Ready

#1558 Fix typo error
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DirectoryService.cpp
  src/libPOW/pow.cpp
Labels: Ready

#1557 Adjust vc7 and vc8 test case
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
Labels: Ready

#1559 After Recovery , Support Rejoin for Node not in sharding structure
  src/depends/libDatabase/OverlayDB.cpp
  src/depends/libDatabase/OverlayDB.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libDirectoryService/DirectoryService.cpp
  src/libLookup/Lookup.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libPersistence/ContractStorage.cpp
  src/libPersistence/ContractStorage.h
  src/libPersistence/Retriever.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1564 Add new dependencies to images
  docker/Dockerfile
  docker/Dockerfile.cuda
  docker/dev/Dockerfile.k8s
Labels: Ready

#1565 Add mutexes in BlockStorage
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
Labels: Ready

#1567 Fix missing setuptools
  docker/Dockerfile
Labels: Ready, high

#1568 Fix corner case when INCRDB_DSNUMS_WITH_STATEDELTAS is 1
  src/libLookup/Lookup.cpp
Labels: Ready, bug

#1569 Used requests package instead of request
  docker/Dockerfile
  docker/Dockerfile.cuda
Labels: Ready

#1570 Added deps futures to docker
  docker/Dockerfile
  docker/Dockerfile.cuda
Labels: Ready

#1573 Add missing setuptools in cuda dockerfile
  docker/Dockerfile.cuda
Labels: Ready

#1574 Revert blacklist clearing for lookup
  src/libNode/DSBlockProcessing.cpp
Labels: Ready

#1577 Fix RejoinAsNormal after any failures
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPersistence/BlockStorage.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready, bug
