Repository Zilliqa/Zilliqa, pull requests merged in 2019-01, with the labels that each got.

#1125 Signature verification on Gossip FORWARD Message type sent via SendRumorToForeignPeer
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
  src/libNetwork/RumorManager.cpp
  src/libNetwork/RumorManager.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1082 Script for generating csv-style shard table from lookup zilliqa log
  scripts/list_shards.py
Labels: Ready

#1099 Refactor DataConversion
  src/cmd/GetAddressFromPubKey.cpp
  src/cmd/GetPubKeyFromPrivKey.cpp
  src/cmd/gen_sign_initial_ds.cpp
  src/cmd/gentxn.cpp
  src/cmd/main.cpp
  src/cmd/sendcmd.cpp
  src/cmd/signmultisig.cpp
  src/libConsensus/ConsensusCommon.cpp
  src/libCrypto/MultiSig.h
  src/libCrypto/Schnorr.h
  src/libData/BlockData/BlockHeader/BlockHashSet.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Synchronizer.cpp
  src/libMediator/Mediator.cpp
  src/libMessage/Messenger.cpp
  src/libNetwork/Guard.cpp
  src/libNetwork/P2PComm.cpp
  src/libNetwork/PeerManager.cpp
  src/libNetwork/RumorManager.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/PoWProcessing.cpp
  src/libPOW/pow.cpp
  src/libProtoServer/Server.cpp
  src/libServer/JSONConversion.cpp
  src/libServer/Server.cpp
  src/libUtils/DataConversion.cpp
  src/libUtils/DataConversion.h
  src/libUtils/UpgradeManager.cpp
  tests/Crypto/Test_Sha2.cpp
  tests/Data/Test_Block.cpp
  tests/Data/Test_Contract.cpp
  tests/Data/Test_Get_Txn.cpp
  tests/Persistence/Test_DSPersistence.cpp
  tests/Zilliqa/test_zilliqa_NAT.py
Labels: Ready, enhancement

#1151 Remove << and string() from privkey
  src/libCrypto/Schnorr.h
Labels: Ready, enhancement

#1145 EIP checksum
  src/libServer/AddressChecksum.h
  tests/Data/CMakeLists.txt
  tests/Data/Test_EIP.cpp
Labels: Ready, rebased

#1093 Change coinbase to exclude
  src/libDirectoryService/Coinbase.cpp
  src/libDirectoryService/DirectoryService.h
Labels: Ready

#1154 Update with master
  src/libServer/AddressChecksum.h
Labels: Ready

#1147 Add "_this_address" in init.json
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/Account.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/MessengerAccountStoreBase.cpp
  tests/Data/Test_Account.cpp
Labels: Ready

#1150 Finish TODO task for POW module
  src/libDirectoryService/DSBlockPreProcessing.cpp
Labels: Ready

#1155 Added signature to DSMicroBlockSubmission
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/MicroBlockPostProcessing.cpp
Labels: Ready

#1160 Pin the last working scilla image in Dockerfile
  docker/Dockerfile
  docker/Dockerfile.cuda
  docker/Makefile
  docker/dev/Dockerfile
Labels: Ready

#1161 Change license
  docker/Dockerfile
  docker/Dockerfile.cuda
  docker/dev/Dockerfile
  docker/dev/Dockerfile.ci
  docker/dev/Dockerfile.k8s
  src/depends/common/Common.cpp
  src/depends/libDatabase/LevelDB.cpp
  src/depends/libDatabase/LevelDB.h
  src/depends/libTrie/Trie.cpp
  src/depends/libTrie/Trie.h
Labels: Ready

#1162 Make local test work
  constants_local.xml
  tests/Zilliqa/test_zilliqa_lookup.py
Labels: Ready

#1168 Roll back OpenSSL to 1.0.2g
  CMakeLists.txt
  README.md
  scripts/ci_install_deps.sh
  src/libCrypto/Schnorr.cpp
Labels: Ready

#1165 Add lower and higher watermark on bytes read
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
Labels: Ready

#1169 Temporarily disable blacklist when recover-all or upgrading
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNetwork/Blacklist.cpp
  src/libNetwork/Blacklist.h
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready, bug

#1171 Implement BN_generate_dsa_nonce
  src/libCrypto/CMakeLists.txt
  src/libCrypto/Schnorr.cpp
  src/libCrypto/generate_dsa_nonce.c
  src/libCrypto/generate_dsa_nonce.h
Labels: Ready

#1170 Remove archival code
  CMakeLists.txt
  README.md
  build.sh
  constants.xml
  constants_local.xml
  docker/Dockerfile
  docker/Dockerfile.cuda
  docker/dev/Dockerfile
  src/CMakeLists.txt
  src/common/Constants.cpp
  src/common/Constants.h
  src/libArchival/Archival.cpp
  src/libArchival/Archival.h
  src/libArchival/ArchiveDB.cpp
  src/libArchival/ArchiveDB.h
  src/libArchival/BaseDB.cpp
  src/libArchival/BaseDB.h
  src/libArchival/CMakeLists.txt
  src/libArchival/ExplorerDB.cpp
  src/libArchival/ExplorerDB.h
  src/libLookup/CMakeLists.txt
  src/libLookup/Lookup.cpp
  src/libMediator/Mediator.cpp
  src/libMediator/Mediator.h
  src/libNode/CMakeLists.txt
  src/libNode/Node.cpp
  src/libPersistence/Retriever.cpp
  src/libUtils/UpgradeManager.cpp
  src/libValidator/Validator.cpp
  src/libZilliqa/CMakeLists.txt
  src/libZilliqa/Zilliqa.cpp
  src/libZilliqa/Zilliqa.h
  tests/Mediator/Test_Mediator.cpp
  tests/Mediator/constants.xml
  tests/Node/test_node_archival.sh
  tests/Zilliqa/test_zilliqa_archival.py
Labels: Ready

#1172 Avoid gossiping challenge if there is only one consensus subset
  src/libConsensus/ConsensusLeader.cpp
Labels: Ready

#1163 Add timeout for waiting pow result from mining proxy
  src/libNode/PoWProcessing.cpp
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  tests/POW/test_RemoteMine.cpp
Labels: Ready

#1146 Avoid asking for data from multiplier but only from lookup
  constants.xml
  constants_local.xml
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
Labels: Ready

#1174 Add checks for raise pow
  src/libDirectoryService/DirectoryService.cpp
  src/libLookup/Lookup.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
Labels: Ready, bug, enhancement

#1175 Remove unused function GetOneGoodKeyPair and unneccessary log from Zilliqa daemon
  daemon/ZilliqaDaemon.cpp
  src/libNode/Node.cpp
Labels: Ready

#1152 Refactor BlockHeader / Add version in BlockHeaderBase / Modify Block Operator
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/BlockData/Block.h
  src/libData/BlockData/Block/BlockBase.cpp
  src/libData/BlockData/BlockHeader/BlockHeaderBase.cpp
  src/libData/BlockData/BlockHeader/BlockHeaderBase.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.cpp
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.h
  src/libData/BlockData/BlockHeader/MicroBlockHeader.cpp
  src/libData/BlockData/BlockHeader/MicroBlockHeader.h
  src/libData/BlockData/BlockHeader/TxBlockHeader.cpp
  src/libData/BlockData/BlockHeader/TxBlockHeader.h
  src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
  src/libData/BlockData/BlockHeader/VCBlockHeader.h
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Synchronizer.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.h
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libServer/JSONConversion.cpp
  tests/Data/Test_Block.cpp
  tests/Lookup/Test_LookupNodeForDSBlock.cpp
  tests/Lookup/Test_LookupNodeForTxBlock.cpp
  tests/Persistence/ReadTxBlock.cpp
  tests/Persistence/Test_DSPersistence.cpp
  tests/Persistence/Test_TxPersistence.cpp
  tests/libTestUtils/TestUtils.cpp
Labels: Ready

#1176 Drop duplicate microblocks and remove DS microblock before viewchange
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
Labels: Ready

#1164 Use HashMap Database for Contract State Storage
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/depends/libDatabase/LevelDB.cpp
  src/depends/libDatabase/LevelDB.h
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/Account.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/AccountStoreTrie.tpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.h
  src/libPersistence/ContractStorage.cpp
  src/libPersistence/ContractStorage.h
  tests/Data/ScillaTestUtil.cpp
  tests/Data/ScillaTestUtil.h
  tests/Data/Test_Account.cpp
  tests/Data/Test_Contract.cpp
Labels: Ready

#1179 Add compatibility support for OpenSSL 1.1.0g
  src/libCrypto/CMakeLists.txt
  src/libCrypto/Schnorr.cpp
Labels: Ready

#1180 Add version to sharding structure and ds committee
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/BlockData/Block/FallbackBlockWShardingStructure.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libLookup/Lookup.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libValidator/Validator.cpp
  tests/Message/Test_Messenger_Primitives.cpp
Labels: Ready

#1181 Fix : Send start pow message to all including multiplier
  src/libDirectoryService/DirectoryService.cpp
Labels: Ready, bug

#1178 Add version field to blocklink
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/BlockChainData/BlockLinkChain.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
Labels: Ready

#1103 Scilla upgrading mechanism
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  docker/dev/Dockerfile
  release.sh
  release_scilla/DEBIAN/control
  release_scilla/DEBIAN/postinst
  release_scilla/scilla/.gitignore
  scripts/release.sh
  src/common/Constants.cpp
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/Account.h
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/MBnForwardedTxnEntry.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libMessage/MessengerSWInfo.cpp
  src/libMessage/ZilliqaMessage.proto
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libUtils/SWInfo.cpp
  src/libUtils/SWInfo.h
  src/libUtils/UpgradeManager.cpp
  src/libUtils/UpgradeManager.h
  tests/Data/Test_Account.cpp
  tests/Utils/Test_SWInfo.cpp
  tests/Utils/Test_UpgradeManager.cpp
Labels: Ready

#1184 Resolve build errored issue on Travis
  cmake/InstallG3log.cmake
  scripts/ci_build.sh
Labels: Ready

#1190 Remove redundant check on consensudID for FinalBlockProcessing
  src/libNode/FinalBlockProcessing.cpp
Labels: bug

#1194 Fix README and build.sh
  README.md
  build.sh
Labels: Ready

#1196 Fix TODOs in AccountData
  src/libData/AccountData/AccountStoreBase.tpp
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#1197 Add REQUIRED to find_package Boost
  CMakeLists.txt
Labels: Ready

#1201 Removed excess LOG_MARKER to prevent lookup log bloat
  src/libPersistence/BlockStorage.cpp
  src/libUtils/SWInfo.cpp
Labels: Ready

#1191 Add ENABLE_SCILLA_MULTI_VERSION
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#1193 Zilliqa and Scilla should be released and upgraded separately
  VERSION
  scripts/release.sh
  src/libUtils/UpgradeManager.cpp
Labels: Ready

#1203 Remove or disable unused functions in lookup
  src/common/MessageNames.h
  src/common/Messages.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
Labels: Ready, enhancement

#1206 Add default value for Verifier Path
  constants.xml
  constants_local.xml
Labels: Ready

#1205 Add retrieval of only latest ds epoch
  src/libLookup/Lookup.cpp
Labels: Ready

#1111 Feat/stress fungible token
  src/libData/AccountData/AccountStoreSC.tpp
  tests/Data/ScillaTestUtil.cpp
  tests/Data/ScillaTestUtil.h
  tests/Data/Test_Contract.cpp
Labels: Ready

#1207 Throw exception in RPC
  src/libServer/JSONConversion.cpp
Labels: Untested

#1208 Set member variable after all checks in ProcessGetDSTxBlockMessage
  src/libDirectoryService/ViewChangePreProcessing.cpp
Labels: Ready, bug, enhancement

#1209 Scilla upgrading should use ENABLE_SCILLA_MULTI_VERSION
  scripts/release.sh
Labels: Ready

#1202 Use DNS to resolve ip for lookup and seed nodes
  constants.xml
  constants_local.xml
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNetwork/Blacklist.cpp
  src/libNetwork/Blacklist.h
  src/libNetwork/DataSender.cpp
  src/libNetwork/Peer.cpp
  src/libNetwork/Peer.h
  src/libUtils/IPConverter.cpp
  src/libUtils/IPConverter.h
Labels: Ready

#1216 Modify Lookup Sync Delay to 5 mins
  constants.xml
  constants_local.xml
Labels: Ready

#1211 Put version field in Account and AccountDelta
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/Account.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libMessage/Messenger.cpp
  src/libMessage/ZilliqaMessage.proto
Labels: Ready

#1217 Fix node crash because mod zero
  src/libNetwork/DataSender.cpp
Labels: Ready

#1218 Fix issue where query very high number non-existence blocks can result in OOM
  src/libLookup/Lookup.cpp
Labels: Ready, bug, high

#1213 Fix the wrong implementation of signmultisig
  src/cmd/signmultisig.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libUtils/UpgradeManager.cpp
Labels: Ready, bug

#1214 Protect consensus message buffer, prevent unlimited message
  src/diagnostic/getnetworkhistory.cpp
  src/libConsensus/ConsensusBackup.h
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusCommon.h
  src/libConsensus/ConsensusLeader.h
  src/libData/BlockChainData/BlockLinkChain.h
  src/libData/BlockData/BlockHeader/VCBlockHeader.h
  src/libDirectoryService/Coinbase.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMediator/Mediator.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNetwork/DataSender.cpp
  src/libNetwork/DataSender.h
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
  src/libNetwork/PeerStore.h
  src/libNetwork/RumorManager.cpp
  src/libNetwork/RumorManager.h
  src/libNetwork/ShardStruct.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libValidator/Validator.h
  tests/Persistence/Test_Diagnostic.cpp
  tests/libTestUtils/TestUtils.cpp
  tests/libTestUtils/TestUtils.h
Labels: Ready

#1221 Add scripts/dep_graph.sh
  CMakeGraphVizOptions.cmake
  scripts/dep_graph.sh
Labels: Ready

#1220 Make log messages easier to read for debugging
  src/libDirectoryService/PoWProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libUtils/Logger.cpp
  src/libUtils/Logger.h
Labels: Ready

#1222 Refactor BlockLinkChain class, put implementation into cpp file
  CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/common/CMakeLists.txt
  src/depends/common/CMakeLists.txt
  src/diagnostic/CMakeLists.txt
  src/libConsensus/CMakeLists.txt
  src/libData/BlockChainData/BlockLinkChain.cpp
  src/libData/BlockChainData/BlockLinkChain.h
  src/libData/BlockChainData/CMakeLists.txt
  src/libData/CMakeLists.txt
  src/libLookup/CMakeLists.txt
  src/libMediator/CMakeLists.txt
  src/libMessage/CMakeLists.txt
  src/libPOW/CMakeLists.txt
  src/libPersistence/CMakeLists.txt
  src/libProtoServer/CMakeLists.txt
  src/libRumorSpreading/CMakeLists.txt
  src/libServer/Server.cpp
  src/libUtils/CMakeLists.txt
  src/libValidator/CMakeLists.txt
  src/libValidator/Validator.cpp
  tests/libTestUtils/CMakeLists.txt
Labels: Ready

#1212 Add signature check for LookupSetDirectoryBlocksFromSeed
  src/libLookup/Lookup.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
Labels: Ready, enhancement

#1226 Daemon should use correct port instead of hard-code 30303
  tests/Zilliqa/daemon_restart.py
Labels: Ready, bug

#1215 Store codecache and initdata into db
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/Account.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/AccountStoreTrie.tpp
  src/libMessage/Messenger.cpp
  src/libMessage/ZilliqaMessage.proto
  src/libPersistence/ContractStorage.cpp
  src/libPersistence/ContractStorage.h
  src/libProtoServer/Server.cpp
  src/libProtoServer/Server.h
  src/libProtoServer/ServerResponse.proto
  src/libServer/Server.cpp
  tests/Data/Test_Account.cpp
  tests/Data/Test_Contract.cpp
Labels: Ready

#1225 Changes to method of identification of empty DS and Tx blocks
  src/libLookup/Lookup.cpp
  src/libServer/Server.cpp
Labels: Ready, bug

#1137 Implement timeout for contract transition transaction
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libUtils/SysCommand.h
Labels: Ready

#1227 Log the VC blocks in lookup state log
  src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
  src/libData/BlockData/BlockHeader/VCBlockHeader.h
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libValidator/Validator.cpp
Labels: Ready

#1231 Daemon should follow testnet command option format
  daemon/ZilliqaDaemon_AWS.cpp
  tests/Zilliqa/daemon_restart.py
  tests/Zilliqa/daemon_restart_local.py
Labels: Ready, bug

#1234 Remove DS microblock before retrying consensus due to MISSINGMICROBLOCK
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
Labels: Ready

#1228 Change scilla version to v0.0.4 and bump up Zilliqa version to v3.3.1
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  docker/dev/Dockerfile
  src/libUtils/SWInfo.h
Labels: Ready

#1233 Update Dockerfile.k8s
  docker/dev/Dockerfile.k8s
Labels: Ready

#1237 Make source code more readable
  src/cmd/genkeypair.cpp
  src/libConsensus/ConsensusBackup.cpp
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusLeader.cpp
  src/libConsensus/ConsensusUser.cpp
  src/libCrypto/MultiSig.cpp
  src/libCrypto/Schnorr.cpp
  src/libData/BlockData/BlockHeader/VCBlockHeader.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libMediator/Mediator.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libNetwork/DataSender.cpp
  src/libNetwork/PeerStore.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libValidator/Validator.cpp
  tests/Crypto/Test_MultiSig.cpp
  tests/Crypto/Test_Schnorr.cpp
  tests/Message/Test_Messenger_Consensus.cpp
  tests/Message/Test_Messenger_Primitives.cpp
  tests/Network/Test_PeerStore.cpp
  tests/libTestUtils/TestUtils.cpp
Labels: Ready

#1236 Some scenario will not trigger upgrading
  constants.xml
  constants_local.xml
  src/libLookup/Lookup.cpp
  src/libUtils/UpgradeManager.cpp
Labels: Ready, bug

#1240 Update Dockerfile.k8s
  docker/dev/Dockerfile.k8s
Labels: Ready

#1232 Add AccountBase and refactor protobuf for Account
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/Account.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/AccountStoreTemp.cpp
  src/libData/AccountData/AccountStoreTrie.tpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libPersistence/ContractStorage.cpp
  src/libPersistence/ContractStorage.h
  src/libProtoServer/Server.cpp
  src/libServer/Server.cpp
  tests/Data/Test_Account.cpp
  tests/Data/Test_Contract.cpp
Labels: Ready

#1239 Change required field in protobuf to optional for Persistent data
  src/libMessage/Messenger.cpp
  src/libMessage/MessengerSWInfo.cpp
  src/libMessage/ZilliqaMessage.proto
Labels: Ready

#1242 Fix shebang and file extension
  scripts/validateBackupDB.sh
  tests/Node/test_node_validateBackupDB.sh
Labels: Ready

#1241 Add getnetworkhistory to install output directory
  CMakeLists.txt
  scripts/dep_graph.sh
Labels: Ready

#1238 Fix protobuf signature signing
  src/libMessage/Messenger.cpp
  src/libMessage/ZilliqaMessage.proto
Labels: Ready, enhancement

#1249 Fix mac-os compile failed for clang-902.0.39.2
  src/libMediator/Mediator.cpp
  src/libUtils/DataConversion.cpp
Labels: Ready, bug

#1247 Add pubkey to the consensus message, verify signature before buffer it
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusCommon.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/MicroBlockPostProcessing.cpp
  tests/Message/Test_Messenger_Consensus.cpp
Labels: Ready

#1246 Fix bug for retrieving sharding structure crash
  scripts/validateBackupDB.sh
  src/libNode/Node.cpp
  tests/Zilliqa/test_zilliqa_local.py
Labels: Ready, bug

#1248 Update AccountStore::RetriveFromDisk for Protobuf
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStoreTrie.tpp
Labels: Ready

#1252 Added difficulty level to the state log message
  src/libNode/DSBlockProcessing.cpp
Labels: Ready

#1253 Change Zilliqa version to v3.4.0
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1258 [release-3.4] Daemon with new recover-all mode should send syncType = RECOVERY_ALL_SYNC
  daemon/ZilliqaDaemon_AWS.cpp
Labels: Ready, bug

#1260 [release-3.4] Move pow MAX_ADJUST_THREAD to constants.xml
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DirectoryService.cpp
Labels: Ready

#1266 [Release3.4] Fix correct return value for ProcessMessageCommitCore
  src/libConsensus/ConsensusLeader.cpp
Labels: Ready, enhancement

#1255 Daemon with new recover-all mode should send syncType = RECOVERY_ALL_SYNC
  daemon/ZilliqaDaemon_AWS.cpp
Labels: Ready, bug

#1259 Move pow MAX_ADJUST_THREAD to constants.xml
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DirectoryService.cpp
Labels: Ready

#1265 Fix correct return value for ProcessMessageCommitCore
  src/libConsensus/ConsensusLeader.cpp
Labels: Ready, enhancement

#1262 [release-3.4] Change Zilliqa version to v3.4.1
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1261 Change Zilliqa version to v3.4.1
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1254 Added report_lookup script for state log checking
  scripts/report_lookup.sh
Labels: Ready

#1269 Provide verifymultisig for rolling-upgrading script
  CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/verifymultisig.cpp
Labels: Ready

#1268 After DS consensus, state delta could be removed
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libValidator/Validator.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1267 Avoid index collision for contract state storage
  src/libPersistence/ContractStorage.cpp
  src/libPersistence/ContractStorage.h
Labels: Ready

#1272 Added monitoring script for normal node
  scripts/report_normal.sh
Labels: Ready

#1281 Remove stale FIXMEs
  src/libConsensus/ConsensusLeader.cpp
  src/libServer/Server.cpp
Labels: Ready

#1274 Revise Schnorr components
  src/libConsensus/ConsensusBackup.cpp
  src/libConsensus/ConsensusLeader.cpp
  src/libCrypto/BIGNUMSerialize.cpp
  src/libCrypto/CMakeLists.txt
  src/libCrypto/ECPOINTSerialize.cpp
  src/libCrypto/MultiSig.cpp
  src/libCrypto/PrivKey.cpp
  src/libCrypto/PubKey.cpp
  src/libCrypto/Schnorr.cpp
  src/libCrypto/Schnorr.h
  src/libCrypto/Signature.cpp
Labels: Ready

#1284 [Release 3.4] Change default port to 33333
  constants.xml
  constants_local.xml
  tests/Mediator/constants.xml
  tests/Network/Test_P2PComm.cpp
Labels: Ready

#1285 Enforce checking of Deserialize result in Messenger
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
Labels: Ready

#1286 SHARD_SIZE_TOLERANCE_LO cannot be greater than current shard size
  constants.xml
  constants_local.xml
  src/libUtils/ShardSizeCalculator.cpp
Labels: Ready, bug

#1287 Fix for UpdateProcessedTxn
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready

#1275 Fix No Transaction Forwarded From DS After View Change
  CMakeLists.txt
  build.sh
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/Account.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libPersistence/ContractStorage.cpp
  src/libPersistence/ContractStorage.h
Labels: Ready

#1273 Fix recovery issue for node not joining network
  src/libLookup/Lookup.cpp
  src/libNode/Node.cpp
  src/libValidator/Validator.cpp
Labels: Ready, bug

#1290 Log cleanup
  src/libConsensus/ConsensusLeader.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/MessengerAccountStoreBase.cpp
  src/libNetwork/Blacklist.cpp
  src/libNetwork/DataSender.cpp
  src/libNetwork/P2PComm.cpp
  src/libNetwork/PeerManager.cpp
  src/libNetwork/RumorManager.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackPostProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/Node.cpp
  src/libPersistence/BlockStorage.cpp
  src/libRumorSpreading/RumorStateMachine.cpp
  src/libUtils/Logger.cpp
  src/libUtils/Logger.h
Labels: Ready

#1292 Clear diagnostic data from previous runs
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1289 New upgrade mechanism
  scripts/ci_install_deps.sh
  scripts/release.sh
Labels: Ready

#1296 Log cleanup 2
  src/libConsensus/ConsensusBackup.cpp
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusLeader.cpp
  src/libCrypto/BIGNUMSerialize.cpp
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/MBnForwardedTxnEntry.h
  src/libData/BlockData/Block/BlockBase.h
  src/libData/BlockData/Block/FallbackBlockWShardingStructure.cpp
  src/libData/BlockData/Block/TxBlock.h
  src/libData/BlockData/BlockHeader/BlockHashSet.h
  src/libData/BlockData/BlockHeader/BlockHeaderBase.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libData/BlockData/BlockHeader/FallbackBlockHeader.h
  src/libData/BlockData/BlockHeader/MicroBlockHeader.h
  src/libData/BlockData/BlockHeader/TxBlockHeader.h
  src/libData/BlockData/BlockHeader/VCBlockHeader.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libMediator/Mediator.cpp
  src/libMessage/Messenger.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FallbackBlockProcessing.cpp
  src/libNode/FallbackPreProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libUtils/Logger.h
  src/libUtils/SWInfo.h
  src/libUtils/TimestampVerifier.h
Labels: Ready

#1294 Added diagnostic db for coinbase reward history
  CMakeLists.txt
  src/diagnostic/CMakeLists.txt
  src/diagnostic/getnetworkhistory.cpp
  src/diagnostic/getrewardhistory.cpp
  src/libDirectoryService/Coinbase.cpp
  src/libDirectoryService/DirectoryService.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libZilliqa/Zilliqa.cpp
  tests/Persistence/Test_Diagnostic.cpp
Labels: Ready

#1301 Fixes in server.cpp
  src/libServer/Server.cpp
  src/libServer/Server.h
Labels: Untested

#1309 Add PoW soln to DS PoW list if difficulty is higher
  src/libDirectoryService/PoWProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
Labels: Ready

#1312 DS difficulty adjust compare with NUM_DS_ELECTION
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  tests/Mediator/constants.xml
  tests/POW/test_POW.cpp
Labels: Ready

#1311 Cleaned up logs for shard node
  src/libData/AccountData/TransactionReceipt.h
  src/libData/BlockChainData/BlockLinkChain.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libLookup/Lookup.cpp
  src/libNetwork/DataSender.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
  src/libPersistence/BlockStorage.cpp
Labels: Ready

#1313 Check return value of ProcessStateDeltaFromFinalBlock in ProcessFinal…
  src/libNode/FinalBlockProcessing.cpp
Labels: Ready

#1307 Check prevHash in validator and GetDSBlock
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libValidator/Validator.cpp
Labels: Ready

#1315 Add epoch number to vc test scenarios logs
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready, enhancement

#1314 Refactor JSONUtils to improve performance
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/TransactionReceipt.cpp
  src/libPersistence/ContractStorage.cpp
  src/libUtils/JsonUtils.h
  tests/Data/ScillaTestUtil.cpp
  tests/Data/Test_Contract.cpp
Labels: Ready

#1317 Fix compile error for dm1
  src/libNode/Node.cpp
Labels: Ready, bug

#1318 Revert reordering of ProcessStateDeltaFromFinalBlock in ProcessFinalBlock
  src/libNode/FinalBlockProcessing.cpp
Labels: Ready

#1319 To v3.5.1
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1320 use dsguard statefulset to identify dsguard pods
  scripts/release.sh
Labels: Ready, bug

#1323 Refactor some data types
  src/libConsensus/ConsensusCommon.cpp
  src/libConsensus/ConsensusCommon.h
  src/libData/BlockChainData/BlockLinkChain.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libNode/PoWProcessing.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
Labels: Ready

#1325 Fix fetch lookup pod since index label is gone
  scripts/release.sh
Labels: bug

#1324 Address Security Audit regarding to AccountStore
  src/libData/AccountData/AccountStoreSC.tpp
  src/libNode/FinalBlockProcessing.cpp
Labels: Ready

#1329 dsguard and shard should wake up at the same time
  scripts/release.sh
Labels: Ready, bug

#1330 Fix wrong test scenario (DM6) name
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready, enhancement

#1333 Fix protobuf initialization for NodeGetGuardNodeNetworkInfoUpdate
  src/libMessage/Messenger.cpp
Labels: Ready, bug

#1332 Prefecth the POD Info
  scripts/release.sh
Labels: Ready

#1327 Limit size of txn packet
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
Labels: Ready

#1334 Change Guard data storage structure to set
  src/libCrypto/Schnorr.h
  src/libNetwork/Guard.cpp
  src/libNetwork/Guard.h
Labels: Untested

#1340 Refine InitContract
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/Account.h
Labels: Ready, enhancement

#1345 Upgrade to scilla v0.1.0
  docker/Dockerfile
  docker/Dockerfile.cuda
  docker/dev/Dockerfile
Labels: Ready, high

#1349 Fix bug for upgrading both zilliqa and scilla
  scripts/release.sh
Labels: bug

#1350 Increase ulimit
  scripts/release.sh
Labels: Ready

#1347 Python script for monitoring mainnet from bastion
  scripts/report_bastion.py
  scripts/stall_checker.py
Labels: Ready

#1348 Fix receipt cumulative gas when deployment failed
  src/libData/AccountData/AccountStoreSC.tpp
  tests/Data/Test_Account.cpp
Labels: Ready, bug, high

#1343 [UnitTest] Fix/Test_Account
  tests/Data/Test_Account.cpp
Labels: Ready

#1351 Scilla to v0.1.1
  docker/Dockerfile
  docker/Dockerfile.cuda
  docker/dev/Dockerfile
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
Labels: in-progress, on hold

#1355 Cleanup logs
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libNetwork/Guard.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1359 Change port number to 33133
  constants.xml
  constants_local.xml
  tests/Network/Test_P2PComm.cpp
Labels: Ready

#1358 Adjust the criteria for epoch num check when receiving packet from neighbors
  src/libNode/Node.cpp
Labels: Ready

#1361 Clean more log messages in the shard node
  src/libConsensus/ConsensusLeader.cpp
  src/libCrypto/MultiSig.cpp
  src/libMessage/Messenger.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
Labels: Ready

#1363 The utility 'parallel' has some bug
  scripts/release.sh
Labels: Ready, bug

#1364 Add a flag to avoid process txn packet in the inappropriate timing
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready
