Repository Zilliqa/Zilliqa, pull requests merged in 2019-11, with the labels that each got.

#1921 Support for fetching coinbase info for specific txblock
  src/common/Messages.h
  src/libData/CMakeLists.txt
  src/libData/CoinbaseData/CMakeLists.txt
  src/libData/CoinbaseData/CoinbaseStruct.cpp
  src/libData/CoinbaseData/CoinbaseStruct.h
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMessage/CMakeLists.txt
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
Labels: feature request

#1925 State hashing optimization via buffering
  src/libData/AccountData/AccountStore.h
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready

#1927 Fix compile error due to old Schnorr usage
  src/libMessage/Messenger.cpp
Labels: Ready

#1928 Fix pubkey and signature serialization code
  src/libNetwork/RumorManager.cpp
  src/libPersistence/BlockStorage.cpp
Labels: Ready

#1922 Make txblock check in Node::CheckIntegrity threaded
  src/cmd/restore.cpp
  src/libLookup/Lookup.cpp
  src/libMediator/Mediator.cpp
  src/libMediator/Mediator.h
  src/libNode/Node.cpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libPersistence/Retriever.cpp
  src/libUtils/ThreadPool.h
  src/libValidator/Validator.cpp
  src/libValidator/Validator.h
  src/libZilliqa/Zilliqa.h
  tests/Data/AccountData/Test_Transaction.cpp
  tests/Persistence/Test_TxPersistence.cpp
Labels: Ready

#1911 [Release-5.1] Keep Updating coinbase during syncup of DS Node
  src/libLookup/Lookup.cpp
Labels: Ready

#1929 Keep Updating coinbase during syncup of DS Node
  src/libLookup/Lookup.cpp
Labels: feature request

#1931 Remove obsolete files and strip utilities binaries
  daemon/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/data_migrate.cpp
  src/diagnostic/CMakeLists.txt
  tests/Zilliqa/filebeat.yml
  tests/Zilliqa/logstash.conf
Labels: enhancement

#1935 support uploading to incremental db every two epoch instead of one epoch
  scripts/upload_incr_DB.py
Labels: Ready

#1930 Separate gas limits for shard and DS microblocks
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.h
Labels: Ready

#1932 Allow consensus leader to send to node in relaxed blacklist
  src/libConsensus/ConsensusLeader.cpp
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
Labels: Ready

#1937 Fix bug for feeding balance when invoking interpreter
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#1729 Pending Txns API
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/MempoolEnum.h
  src/common/Messages.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libServer/LookupServer.cpp
  src/libServer/LookupServer.h
Labels: Ready

#1923 Zilliqa Websocket Server
  constants.xml
  constants_local.xml
  src/cmd/CMakeLists.txt
  src/cmd/websocketsubscriber.cpp
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/FinalBlockProcessing.cpp
  src/libServer/CMakeLists.txt
  src/libServer/LookupServer.cpp
  src/libServer/LookupServer.h
  src/libServer/WebsocketServer.cpp
  src/libServer/WebsocketServer.h
  src/libZilliqa/Zilliqa.cpp
Labels: Ready, feature request

#1926 Enable ds node re-join faster not waiting until next vacuous epoch
  src/common/Messages.h
  src/libDirectoryService/Coinbase.cpp
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMessage/Messenger.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libZilliqa/Zilliqa.cpp
  tests/Incentives/test_coinbase.cpp
Labels: Ready, feature request

#1941 Set different gas limit default values for easier testing
  constants.xml
  constants_local.xml
Labels: Ready

#1936 Scilla multi-message support
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/Account.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/TransactionReceipt.cpp
  src/libData/AccountData/TransactionReceipt.h
  src/libPersistence/Retriever.cpp
  src/libPersistence/Retriever.h
  tests/Data/AccountData/Test_AccountStore.cpp
  tests/Data/Test_Contract.cpp
Labels: Ready

#1940 To v5.2.0-alpha.0
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1943 [Release-5.2] Avoid sending request for blacklist removal by lookup nodes
  src/libNode/Node.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1942 Avoid sending request for blacklist removal by lookup nodes
  src/libNode/Node.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready, bug

#1944 [Release-5.2] Send Blacklist removal request for shard guard as well
  src/libNode/Node.cpp
Labels: Ready, bug

#1945 Send Blacklist removal request for shard guard as well
  src/libNode/Node.cpp
Labels: Ready
