Repository Zilliqa/Zilliqa, pull requests merged in 2019-09, with the labels that each got.

#1792 Avoid deserialization in CheckIntegrity
  src/libNode/Node.cpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
Labels: Ready

#1793 Force serialization of primitive proto fields for block and tx data
  src/libMessage/ZilliqaMessage.proto
Labels: Ready

#1794 Check the correctness of hash inside the block
  src/libValidator/Validator.cpp
Labels: Ready

#1798 Fix genesis DS block hash not correct problem
  src/common/Constants.h
  src/libLookup/Synchronizer.cpp
  src/libLookup/Synchronizer.h
  tests/Message/CMakeLists.txt
  tests/Message/Test_Messenger_Compatibility.cpp
Labels: Ready

#1791 Enable fetching missing mbs/txns from lookup for seed nodes
  CMakeLists.txt
  build.sh
  constants.xml
  constants_local.xml
  scripts/make_image_for_test.sh
  src/common/Constants.cpp
  src/common/Constants.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNetwork/Blacklist.cpp
  src/libNetwork/Blacklist.h
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready, feature request

#1799 Use exists function in CheckTxBody
  src/libPersistence/BlockStorage.cpp
Labels: Ready

#1801 Fix misleading comments
  constants.xml
  constants_local.xml
Labels: Ready

#1800 Fix possible race cond
  src/libLookup/Lookup.cpp
Labels: Ready

#1743 Contract map storage & Scilla IPC
  cmake/InstallJsonrpccpp.cmake
  constants.xml
  constants_local.xml
  docker/Dockerfile
  docker/Dockerfile.cuda
  docker/dev/Dockerfile
  src/cmd/CMakeLists.txt
  src/cmd/data_migrate.cpp
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/Account.h
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/CMakeLists.txt
  src/libData/AccountData/TransactionReceipt.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libMessage/CMakeLists.txt
  src/libMessage/Messenger.cpp
  src/libMessage/ZilliqaMessage.proto
  src/libNode/FinalBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/CMakeLists.txt
  src/libPersistence/ContractStorage.h
  src/libPersistence/ContractStorage2.cpp
  src/libPersistence/ContractStorage2.h
  src/libPersistence/Retriever.cpp
  src/libPersistence/Retriever.h
  src/libPersistence/ScillaMessage.proto
  src/libProtoServer/CMakeLists.txt
  src/libProtoServer/Server.cpp
  src/libServer/CMakeLists.txt
  src/libServer/LookupServer.cpp
  src/libServer/ScillaIPCServer.cpp
  src/libServer/ScillaIPCServer.h
  src/libServer/Server.h
  src/libServer/StatusServer.cpp
  src/libUtils/SysCommand.h
  tests/CMakeLists.txt
  tests/Data/AccountData/CMakeLists.txt
  tests/Data/AccountData/Test_Account.cpp
  tests/Data/AccountData/Test_AccountStore.cpp
  tests/Data/ScillaTestUtil.cpp
  tests/Data/Test_Contract.cpp
  tests/Message/CMakeLists.txt
  tests/Server/CMakeLists.txt
  tests/Server/Test_ScillaIPCServer.cpp
Labels: Ready

#1804 Return code & data if they are present
  src/libServer/JSONConversion.cpp
Labels: Untested

#1803 Integrate fetching a substate of a smart contract
  src/libServer/JSONConversion.cpp
  src/libServer/JSONConversion.h
  src/libServer/LookupServer.cpp
  src/libServer/LookupServer.h
Labels: Ready

#1802 To v5.0.0-alpha.0
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1807 fix mode check
  src/libLookup/Lookup.cpp
Labels: Ready

#1808 Add data_migrate to bin folder
  CMakeLists.txt
Labels: Ready

#1809 [release-5.0] Add data_migrate to bin folder
  CMakeLists.txt
Labels: Ready

#1810 Seednodes to skip itself adding to lookupnodes
  src/libLookup/Lookup.cpp
  src/libNode/Node.cpp
Labels: Ready

#1812 [Release 5.0] Seednodes to skip itself adding to lookupnodes
  src/libLookup/Lookup.cpp
  src/libNode/Node.cpp
Labels: Ready

#1818 [release-5.0] Fixes for Smart Contract execution on empty map key & RevertCommitTemp
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/AccountStoreSC.tpp
  src/libMessage/Messenger.cpp
  src/libPersistence/ContractStorage2.cpp
  tests/Data/AccountData/Test_AccountStore.cpp
Labels: Ready

#1819 [release-5.0] Fix unnecessary mutex
  src/libDirectoryService/ViewChangePostProcessing.cpp
Labels: Ready

#1816 To v5.0.0-alpha.1
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1817 Fix unnecessary mutex
  src/libDirectoryService/ViewChangePostProcessing.cpp
Labels: bug

#1815 Fixes for Smart Contract execution on empty map key & RevertCommitTemp
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/AccountStoreSC.tpp
  src/libMessage/Messenger.cpp
  src/libPersistence/ContractStorage2.cpp
  tests/Data/AccountData/Test_AccountStore.cpp
Labels: Ready

#1822 Fix recover community testnet lookup and it crash
  src/libLookup/Lookup.cpp
Labels: Ready

#1824 [release-5.0] Add an IPC unit test for empty string map key
  tests/Server/Test_ScillaIPCServer.cpp
Labels: Ready

#1821 Add option to ignore scilla checker for outdated contract
  src/cmd/data_migrate.cpp
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libPersistence/ContractStorage2.cpp
  src/libPersistence/ContractStorage2.h
  src/libPersistence/Retriever.cpp
  src/libPersistence/Retriever.h
Labels: Ready

#1827 [Release-5.0] Start listening when lookup finish sync
  src/libLookup/Lookup.cpp
Labels: Ready

#1828 Start listening when lookup finish sync
  src/libLookup/Lookup.cpp
Labels: Ready

#1834 [Release 5.0] skip myip while sending to random lookup
  src/libLookup/Lookup.cpp
Labels: Ready

#1835 [Release-5.0] Fixing migrated state quoting
  src/libData/AccountData/AccountStore.cpp
  src/libPersistence/ContractStorage2.cpp
Labels: Ready

#1833 skip myip while sending to random lookup
  src/libLookup/Lookup.cpp
Labels: Ready

#1831 Fixing migrated state quoting
  src/libData/AccountData/AccountStore.cpp
  src/libPersistence/ContractStorage2.cpp
Labels: Ready

#1839 [Release-5.0] Don't update contract states every epoch & export contract addresses during migration
  src/cmd/data_migrate.cpp
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libPersistence/Retriever.cpp
  src/libPersistence/Retriever.h
Labels: Ready

#1841 patch SCILLA_IPC_SOCKET_PATH for local test
  tests/Zilliqa/test_zilliqa_local.py
Labels: Ready

#1842 [Release 5.0] patch SCILLA_IPC_SOCKET_PATH for local test
  tests/Zilliqa/test_zilliqa_local.py
Labels: Ready

#1849 [Release-5.0] Fix recovered lookup start to listening crash
  src/libLookup/Lookup.cpp
Labels: Ready

#1844 [Release-5.0] Fix Delete Index
  src/cmd/data_migrate.cpp
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libPersistence/ContractStorage2.cpp
  src/libPersistence/ContractStorage2.h
  src/libPersistence/Retriever.cpp
  src/libPersistence/Retriever.h
Labels: Ready

#1851 [Release-5.0] Add mutex for ContractStorage2
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStoreSC.tpp
  src/libPersistence/ContractStorage2.cpp
  src/libPersistence/ContractStorage2.h
Labels: Ready

#1852 [Release-5.0] Don't start lookup server if lookup still syncing
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1854 [Release 5.0] Avoid setting NO_SYNC for recovery of normal nodes
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1845 Fix recovered lookup start to listening crash
  src/libLookup/Lookup.cpp
Labels: Ready

#1856 Don't start lookup server if lookup still syncing
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1838 Don't update contract states every epoch & export contract addresses during migration
  src/cmd/data_migrate.cpp
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStore.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libPersistence/ContractStorage2.cpp
  src/libPersistence/ContractStorage2.h
  src/libPersistence/Retriever.cpp
  src/libPersistence/Retriever.h
Labels: Ready

#1865 [Release-5.0] Fix thread invocation
  src/libServer/LookupServer.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1858 multiple fixes for recovery
  src/libLookup/Lookup.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1867 Fix thread invocation
  src/libServer/LookupServer.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1872 Preserve quotes in GetSmartContractSubState
  src/libServer/JSONConversion.cpp
Labels: Ready

#1813 seed nodes and l2l to fetch any missing mb from last N epoch and Rejoin optimization
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
Labels: Ready, enhancement

#1874 Remove data_migrate from build
  CMakeLists.txt
  src/cmd/CMakeLists.txt
Labels: Ready

#1873 Update jsonrpccpp to 1.2.0
  CMakeLists.txt
  cmake/InstallJsonrpccpp.cmake
  src/depends/safeserver/CMakeLists.txt
  src/depends/safeserver/safelinuxtcpsocketserver.cpp
  src/depends/safeserver/safelinuxtcpsocketserver.h
  src/depends/safeserver/safetcpsocketserver.cpp
  src/depends/safeserver/safetcpsocketserver.h
  src/libData/AccountData/AccountStore.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1877 Fix test pow on travis sometimes fail
  tests/POW/test_POW.cpp
Labels: Ready

#1881 Add lookup option for sending contracts to DS committee
  scripts/miner_info.py
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libServer/StatusServer.cpp
  src/libServer/StatusServer.h
Labels: Ready

#1885 Check on min. cpu and ram for mining machine
  src/cmd/main.cpp
  src/libUtils/HardwareSpecification.h
Labels: Ready

#1884 Using bool operator to check address
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/Address.h
  src/libData/AccountData/Transaction.h
  src/libPersistence/ContractStorage.cpp
  src/libPersistence/ContractStorage2.cpp
  src/libProtoServer/Server.cpp
  src/libServer/LookupServer.cpp
  src/libValidator/Validator.cpp
Labels: Ready, enhancement

#1893 Clean up Test_ShardSizeCalculator
  src/libUtils/ShardSizeCalculator.cpp
  tests/Utils/Test_ShardSizeCalculator.cpp
Labels: Ready

#1895 Reduce default MAX_READ_WATERMARK_IN_BYTES in constants files
  constants.xml
  constants_local.xml
Labels: Ready

#1896 Optimize GenerateShardCounts to minimize number of unsharded nodes
  src/libUtils/ShardSizeCalculator.cpp
  src/libUtils/ShardSizeCalculator.h
  tests/Utils/Test_ShardSizeCalculator.cpp
Labels: Ready

#1894 Save consensus leader after view change
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libNode/ViewChangeBlockProcessing.cpp
Labels: Ready
