Repository Zilliqa/Zilliqa, pull requests merged in 2019-07, with the labels that each got.

#1710 Fix log messages for address
  src/libMessage/Messenger.cpp
Labels: Ready

#1711 revert nonblocking connection
  src/libNetwork/P2PComm.cpp
Labels: Ready

#1713 Fix of kubectl cp command
  scripts/release.sh
Labels: Ready, bug

#1714 Check whether account exists when create contract
  src/libData/AccountData/AccountStoreBase.h
  src/libData/AccountData/AccountStoreBase.tpp
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#1712 log popen failure
  src/libUtils/SysCommand.h
Labels: Ready

#1707 Node only do sync if failed to do pow
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/PoWProcessing.cpp
Labels: Ready

#1715 Add timestamp to daemon logging
  daemon/ZilliqaDaemon_AWS.cpp
Labels: Ready

#1709 Fix epochfin for lookup when no shard formed
  src/libNode/FinalBlockProcessing.cpp
Labels: Ready

#1706 Continue check result from proxy until timeout
  src/libPOW/pow.cpp
Labels: Ready

#1708 To v4.7.0
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1724 Update README to v4.7.0
  README.md
Labels: Ready

#1718 Automatically remove ipMapping.xml after using it
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#1722 Remove check for microblock epoch num to match the latest tx block num
  src/libNode/FinalBlockProcessing.cpp
Labels: Ready

#1717 Fix potential concurrency issue for AccountStore::m_state access
  src/libData/AccountData/AccountStore.cpp
  src/libData/AccountData/AccountStoreTrie.tpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
Labels: Ready

#1723 Fix handling of unavailable microblocks
  src/libLookup/Lookup.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.h
Labels: Ready

#1688 Add states during contract creation
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#1651 Support customized log path
  daemon/ZilliqaDaemon_AWS.cpp
  src/cmd/main.cpp
  src/libUtils/Logger.cpp
  src/libUtils/Logger.h
  tests/POW/test_POW.cpp
  tests/Utils/Test_Logger1.cpp
  tests/Utils/Test_Logger2.cpp
  tests/Zilliqa/daemon_restart.py
Labels: Ready, enhancement

#1693 move scripts from testnet to core repo
  scripts/auto_back_up.py
  scripts/downloadIncrDB.py
  scripts/release.sh
  scripts/uploadIncrDB.py
Labels: Ready, enhancement

#1733 Improve validateDB logging and add continueOnError option
  src/cmd/validateDB.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready, enhancement

#1736 Generate pow header hash with peer port
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/PoWProcessing.cpp
  src/libNode/PoWProcessing.cpp
  src/libPOW/pow.cpp
  src/libPOW/pow.h
  tests/POW/CMakeLists.txt
  tests/POW/test_POW.cpp
  tests/POW/test_RemoteMine.cpp
Labels: Ready

#1734 Pick from temp
  scripts/uploadIncrDB.py
Labels: Ready, bug

#1728 Remove redundant mutex
  src/libData/AccountData/AccountStore.cpp
Labels: Ready

#1737 Optimize DS leader verify fail log
  src/libCrypto/PubKey.cpp
  src/libCrypto/Schnorr.h
  src/libLookup/Lookup.cpp
Labels: enhancement

#1738 add checksum check
  scripts/downloadIncrDB.py
Labels: Ready, feature request

#1740 To v4.7.1
  VERSION
  constants.xml
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1742 Update README to v4.7.1
  README.md
Labels: Ready

#1730 Add more lookup checks when creating txn
  src/libServer/LookupServer.cpp
Labels: Ready

#1731 Adjust ds microblock gas limit after view change
  src/libConsensus/ConsensusCommon.h
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libMediator/Mediator.cpp
  src/libMediator/Mediator.h
  src/libMessage/Messenger.cpp
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.h
Labels: Ready
