Repository Zilliqa/Zilliqa, pull requests merged in 2019-04, with the labels that each got.

#1579 Support level2lookup for rolling-upgrading release
  scripts/release.sh
Labels: Ready

#1581 Fix typos in usage description of local test script
  tests/Zilliqa/test_zilliqa_local.py
Labels: Ready

#1583 Fix the DNS resolve issue
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libServer/Server.cpp
Labels: Ready, bug

#1584 [release-4.4] Merging V4.4.1 into release-4.4 branch
  README.md
  VERSION
  cmake/InstallJsonrpccpp.cmake
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libPOW/pow.h
  src/libPersistence/BlockStorage.cpp
  src/libUtils/SWInfo.h
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1580 Find solution in pow list before verify pow from leader
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.h
Labels: Ready, enhancement

#1586 Fix extra libssl-dev in readme
  README.md
Labels: Ready, enhancement

#1593 Remove Contract Accounts If Creation Failed
  src/libData/AccountData/AccountStoreSC.tpp
  tests/Data/AccountData/Test_AccountStore.cpp
Labels: Ready

#1591 Recovery of dsguard
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1588 DS committee exclude ds guard nodes from blacklist
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libLookup/Lookup.cpp
  src/libNode/DSBlockProcessing.cpp
Labels: Ready

#1594 Add responses stats for each subsets
  src/libConsensus/ConsensusLeader.cpp
  src/libConsensus/ConsensusLeader.h
Labels: Ready, Untested

#1596 Fix a peer can connect to another peer with unlimited connections
  constants.xml
  constants_local.xml
  src/common/BaseType.h
  src/common/Constants.cpp
  src/common/Constants.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
  src/libNode/DSBlockProcessing.cpp
Labels: Ready

#1561 LatestEpochStatesUpdated/DetachMoveUpdatesToDisk/MutexInBlockStorage
  src/common/Constants.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libServer/Server.cpp
  src/libServer/Server.h
Labels: Ready

#1595 Put a limit on storage of lookup
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libServer/Server.cpp
  src/libServer/Server.h
Labels: Ready

#1592 Fix Json Conversion For Handling Corner Case Of Contract Txn
  src/libData/AccountData/Account.cpp
  src/libData/AccountData/AccountStoreSC.tpp
  src/libPersistence/ContractStorage.cpp
  src/libUtils/JsonUtils.h
Labels: Ready

#1598 Add RPC for addition to whitelist and removal
  scripts/miner_info.py
  src/libNetwork/Blacklist.cpp
  src/libNetwork/Blacklist.h
  src/libServer/Server.cpp
  src/libServer/Server.h
Labels: Ready

#1599 Handle VC Precheck cornercase
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/ViewChangePostProcessing.cpp
  src/libDirectoryService/ViewChangePreProcessing.cpp
Labels: Untested, bug

#1597 Fix wrong usage of updating DSINCOMPLETED for lookup node
  src/libNode/FinalBlockProcessing.cpp
Labels: Ready

#1603 Fix stateroot failure
  src/libPersistence/Retriever.cpp
Labels: Ready, bug

#1604 Log the check failed pow winner ip address
  src/libDirectoryService/DSBlockPreProcessing.cpp
Labels: Ready

#1609 Auto recovery of seed nodes if lagging due to missing FB and DS blocks
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready, enhancement

#1608 Fix pow test case failed on travis problem
  tests/POW/test_POW.cpp
Labels: Ready

#1612 Fix corner case of safemath
  src/libUtils/SafeMath.tpp
  tests/Utils/Test_SafeMath.cpp
Labels: Ready

#1617 Add size check
  src/libMessage/Messenger.cpp
  src/libNode/Node.cpp
  tests/Data/AccountData/Test_AccountStore.cpp
Labels: Ready

#1614 Check if microblockstatedeltahash null when state delta is empty
  src/libDirectoryService/MicroBlockProcessing.cpp
Labels: Ready

#1622 Minor fixes for AccountStoreSC
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#1618 Adjust gas cost for failed contract transaction
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#1621 DS store and send DSMicroBlock at every epoch
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
Labels: Ready

#1613 Apply atomic state change among contract chain call
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#1627 Fix Invocation sequence for seed nodes.
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1625 Reshuffle the txn-shard map after each ds epoch
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  tests/Lookup/CMakeLists.txt
  tests/Lookup/Test_txn_send.cpp
  tests/libTestUtils/TestUtils.cpp
  tests/libTestUtils/TestUtils.h
Labels: Ready

#1629 Add miner_info.py into release package
  scripts/release.sh
Labels: Ready
