Repository Zilliqa/Zilliqa, pull requests merged in 2019-10, with the labels that each got.

#1897 Catch potential stoull exception
  src/libPersistence/Retriever.cpp
Labels: Ready

#1889 No PoW received, network should progress with DS shard
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/FinalBlockPostProcessing.cpp
  src/libDirectoryService/FinalBlockPreProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libProtoServer/Server.cpp
  src/libServer/LookupServer.cpp
Labels: Ready

#1899 Add support for clang, libfuzzer and undef behavior sanitizer
  CMakeLists.txt
  build.sh
  cmake/InstallJsonrpccpp.cmake
  src/cmd/restore.cpp
  src/depends/NAT/nat.cpp
  src/libCrypto/MultiSig.cpp
  src/libCrypto/PrivKey.cpp
  src/libCrypto/Schnorr.cpp
Labels: enhancement

#1900 Blacklist at 2 levels strict or relaxed to allow incoming msg
  src/libDirectoryService/DirectoryService.cpp
  src/libLookup/Lookup.cpp
  src/libNetwork/Blacklist.cpp
  src/libNetwork/Blacklist.h
  src/libNetwork/DataSender.cpp
  src/libNetwork/Guard.cpp
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
  src/libNode/Node.cpp
  src/libServer/StatusServer.cpp
Labels: Ready

#1901 Fix contract state reverting
  src/libData/AccountData/AccountStoreSC.tpp
  src/libPersistence/ContractStorage2.cpp
Labels: Ready

#1903 Skip txn if txn gaslimit exceeded microblock gaslimit & Some refactoring
  src/cmd/GetAddressFromPubKey.cpp
  src/libCrypto/PubKey.cpp
  src/libCrypto/Schnorr.h
  src/libData/AccountData/AccountStore.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/MicroBlockPreProcessing.cpp
  src/libServer/CMakeLists.txt
  src/libServer/LookupServer.cpp
  src/libServer/LookupServer.h
  src/libValidator/Validator.cpp
  src/libValidator/Validator.h
  tests/Data/AccountData/Test_Transaction.cpp
Labels: Ready

#1904 To v5.1.0-alpha.0
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  docker/dev/Dockerfile
  src/libUtils/SWInfo.h
Labels: Ready

#1902 Support for blacklist removal message
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libLookup/Lookup.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#1905 Shard node try rejoin immediately after being restart
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
  src/libZilliqa/Zilliqa.cpp
Labels: Ready

#1910 Skip duplicate microblock processing earliest before performing any validation
  src/libDirectoryService/MicroBlockProcessing.cpp
Labels: Ready

#1915 [release-5.1] Add lookup option for sending contracts to DS committee
  scripts/miner_info.py
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libServer/StatusServer.cpp
  src/libServer/StatusServer.h
Labels: Ready

#1917 [release-5.1] Revert relaxed blacklist temporarily
  src/libNetwork/Blacklist.cpp
Labels: Ready

#1916 [release-5.1] To v5.1.1
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1912 Fix possible race condition
  src/libDirectoryService/MicroBlockProcessing.cpp
Labels: Ready, bug

#1918 [Release-5.1] Fix the marker url for download
  scripts/download_incr_DB.py
Labels: Ready

#1920 Fix the marker url for download
  scripts/download_incr_DB.py
Labels: Ready

#1913 Add python3 support to local test
  tests/Zilliqa/test_zilliqa_NAT.py
  tests/Zilliqa/test_zilliqa_late.py
  tests/Zilliqa/test_zilliqa_local.py
  tests/Zilliqa/test_zilliqa_lookup.py
Labels: Ready
