Repository Zilliqa/Zilliqa, pull requests merged in 2019-08, with the labels that each got.

#1735 Store txns in DB
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.h
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
Labels: Ready

#1741 Avoid validateDB crashing when checking normal node
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#1739 Don't fetch info from blacklisted seed nodes
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DirectoryService.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libMessage/Messenger.h
  src/libNetwork/DataSender.cpp
  src/libNetwork/DataSender.h
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
  src/libNetwork/RumorManager.cpp
  src/libNetwork/RumorManager.h
  src/libNetwork/ShardStruct.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/Node.cpp
Labels: Ready

#1746 GETSTARTPOW improvement
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNetwork/Peer.cpp
  src/libNetwork/Peer.h
  src/libNode/DSBlockProcessing.cpp
Labels: Ready

#1748 To v4.8.0-alpha.0
  VERSION
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1752 [release-4.7] Daemon should re-launch process with previous synctype
  daemon/ZilliqaDaemon_AWS.cpp
Labels: Ready

#1753 Daemon should re-launch process with previous synctype
  daemon/ZilliqaDaemon_AWS.cpp
Labels: Ready

#1749 Save txns to S3
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.h
  tests/Persistence/Test_TxBody.cpp
Labels: Ready, enhancement

#1758 Add redundant backup
  scripts/uploadIncrDB.py
Labels: Ready

#1757 Fix constant
  constants.xml
  constants_local.xml
Labels: Ready

#1759 Fetch missing statedelta from seed
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/Node.cpp
  src/libPersistence/Retriever.cpp
Labels: Ready

#1755 [release-4.8] Daemon should re-launch process with previous synctype
  daemon/ZilliqaDaemon_AWS.cpp
Labels: Ready

#1761 [release-4.8] Add redundant backup
  scripts/uploadIncrDB.py
Labels: Ready

#1756 [release-4.8] Save txns to S3
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.h
  tests/Persistence/Test_TxBody.cpp
Labels: Ready

#1762 [release-4.8] Fetch missing statedelta from seed
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/Node.cpp
  src/libPersistence/Retriever.cpp
Labels: Ready

#1763 To v4.8.0-alpha.1
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1765 [release-4.8] Added multipart etag support
  scripts/downloadIncrDB.py
Labels: Ready

#1760 Added multipart etag support
  scripts/downloadIncrDB.py
Labels: Ready

#1764 Fix start uploadIncrDB.py with error
  scripts/uploadIncrDB.py
Labels: Ready

#1766 [release-4.8] Fix start uploadIncrDB.py with error
  scripts/uploadIncrDB.py
Labels: Ready

#1770 [release-4.8] fix backup
  scripts/uploadIncrDB.py
Labels: Ready

#1771 To v4.8.0
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#1773 Update README to v4.8.0
  README.md
Labels: Ready

#1774 Use GetEpochFin in auto_back_up.py
  scripts/auto_back_up.py
Labels: Ready

#1726 Sync/rejoin lagging-behind lookup nodes after recovery
  src/common/MessageNames.h
  src/common/Messages.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libNode/FinalBlockProcessing.cpp
  src/libZilliqa/Zilliqa.cpp
Labels: Ready, enhancement

#1775 Missing include mbstxns flag
  src/libNode/Node.cpp
Labels: Ready, bug

#1777 Generate txBodies ldb and optionally json from raw bytes from S3 files
  CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/genTxnBodiesFromS3.cpp
  src/libUtils/FileSystem.cpp
  src/libUtils/FileSystem.h
Labels: Ready, feature request

#1779 add GetTotalSupply API
  src/libServer/LookupServer.cpp
  src/libServer/LookupServer.h
Labels: Ready

#1780 Control txns backup to S3
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready

#1587 Implement the DS Reputation System.
  constants.xml
  constants_local.xml
  src/cmd/restore.cpp
  src/common/Constants.cpp
  src/common/Constants.h
  src/libData/BlockData/BlockHeader/DSBlockHeader.cpp
  src/libData/BlockData/BlockHeader/DSBlockHeader.h
  src/libDirectoryService/CMakeLists.txt
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libDirectoryService/DSBlockPreProcessing.cpp
  src/libDirectoryService/DSComposition.cpp
  src/libDirectoryService/DSComposition.h
  src/libDirectoryService/DirectoryService.h
  src/libLookup/Synchronizer.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/ZilliqaMessage.proto
  src/libNode/DSBlockProcessing.cpp
  src/libNode/Node.h
  src/libNode/ViewChangeBlockProcessing.cpp
  src/libPersistence/Retriever.cpp
  src/libValidator/Validator.cpp
  tests/CMakeLists.txt
  tests/Directory/CMakeLists.txt
  tests/Directory/Test_DetermineByzantineNodes.cpp
  tests/Directory/Test_SaveDSPerformance.cpp
  tests/Directory/Test_UpdateDSComposition.cpp
  tests/Lookup/Test_LookupNodeForDSBlock.cpp
  tests/Lookup/Test_LookupNodeForTxBlock.cpp
  tests/Persistence/Test_DSPersistence.cpp
  tests/libTestUtils/TestUtils.cpp
Labels: Ready

#1784 Fix access null pointer
  src/libNode/Node.cpp
Labels: Ready

#1783 Change default value for small scale test
  constants_local.xml
Labels: Ready

#1782 Fix Blocklink index
  src/libLookup/Lookup.cpp
  src/libNode/DSBlockProcessing.cpp
  src/libNode/PoWProcessing.cpp
Labels: Ready
