Repository Zilliqa/Zilliqa, pull requests merged in 2020-07, with the labels that each got.

#2132 Abort RunConsensusOnViewChange on DS_SYNC
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/ViewChangePreProcessing.cpp
Labels: Ready

#2124 Suppress Mempool_already_present (Error 23)
  src/libNode/Node.cpp
Labels: Ready

#2134 [release-6.3] Abort RunConsensusOnViewChange on DS_SYNC
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/ViewChangePreProcessing.cpp
Labels: Ready

#2136 To Zilliqa v6.3.0-alpha.2 and Scilla v0.7.1
  docker/Dockerfile
  docker/Dockerfile.cuda
  src/libUtils/SWInfo.h
Labels: Ready

#2119 Avoid duplicate txnpkt bufferring and processing
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#2135 Add CHAIN_ID info to message header
  constants_local.xml
  src/libNetwork/P2PComm.cpp
Labels: Ready

#2137 Optimize AddPendingTxn mutex locking code
  src/libNode/FinalBlockProcessing.cpp
Labels: Ready

#2139 Fix logical comparison in GetPendingTxn
  src/libNode/MicroBlockPreProcessing.cpp
Labels: Ready

#2141 [Release-6.3]Fix GetPendingTxn
  src/libNode/MicroBlockPreProcessing.cpp
  src/libServer/LookupServer.cpp
Labels: Ready

#2130 ShardGuard Pod deletion and few optimization/bug fix
  src/common/Messages.h
  src/libDirectoryService/DirectoryService.cpp
  src/libDirectoryService/DirectoryService.h
  src/libLookup/Lookup.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNetwork/P2PComm.cpp
  src/libNetwork/P2PComm.h
  src/libNetwork/RumorManager.cpp
  src/libNetwork/RumorManager.h
  src/libNode/DSBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready

#2151 Fix for possible possible race condition on m_shards
  src/libNode/DSBlockProcessing.cpp
Labels: Ready, bug

#2127 Add websocket to isolated server
  src/cmd/isolated_server.cpp
  src/libServer/IsolatedServer.cpp
  src/libServer/IsolatedServer.h
  src/libServer/WebsocketServer.cpp
Labels: Ready

#2155 Add missing RemoveAccount if deployment failed
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#2153 Add txns dropped due to higher gas txn in the log and dropped txns
  src/libData/AccountData/TxnPool.h
  src/libNode/MicroBlockPreProcessing.cpp
  src/libNode/Node.cpp
  tests/Data/AccountData/Test_TxnPool.cpp
Labels: Ready

#2157 Handle blacklisting of seed node elegantly
  scripts/miner_info.py
  src/libLookup/Lookup.cpp
  src/libNetwork/Blacklist.cpp
  src/libNetwork/Blacklist.h
  src/libNetwork/P2PComm.cpp
  src/libNode/Node.cpp
  src/libServer/StatusServer.cpp
  src/libServer/StatusServer.h
Labels: Ready, feature request

#2156 Allow non-guard shard (miner) nodes to rejoin with new IP in same ds epoch
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/common/Messages.h
  src/libLookup/Lookup.cpp
  src/libMessage/Messenger.cpp
  src/libMessage/Messenger.h
  src/libMessage/ZilliqaMessage.proto
  src/libNode/Node.cpp
  src/libNode/Node.h
Labels: Ready, feature request

#2161 Improve multicast in non-ideal cases with connectivity with some of peers
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libNetwork/P2PComm.cpp
Labels: Ready

#2154 Soft confirmation by earlier forwarding of MB and TxnBodies
  src/libDirectoryService/DirectoryService.h
  src/libDirectoryService/MicroBlockProcessing.cpp
  src/libNode/FinalBlockProcessing.cpp
  src/libNode/MicroBlockPostProcessing.cpp
  src/libNode/Node.h
  src/libServer/JSONConversion.cpp
  src/libServer/JSONConversion.h
  src/libServer/LookupServer.cpp
  src/libServer/LookupServer.h
Labels: Ready
