Repository Zilliqa/Zilliqa, pull requests merged in 2020-01, with the labels that each got.

#1972 Improve get last block efficiency
  src/libData/BlockChainData/BlockChain.h
Labels: enhancement

#1971 Avoid loading all Tx blocks in valdb
  src/libNode/Node.cpp
  src/libPersistence/BlockStorage.cpp
  src/libPersistence/BlockStorage.h
  src/libValidator/Validator.cpp
  src/libValidator/Validator.h
Labels: Ready

#1963 Syncronization beween upload and download incrdb script
  scripts/download_incr_DB.py
  scripts/upload_incr_DB.py
Labels: Ready, feature request

#1977 Fix retryCount corner case
  src/libLookup/Lookup.cpp
Labels: bug

#1982 Add contract transitions in transaction receipt
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/TransactionReceipt.cpp
  src/libData/AccountData/TransactionReceipt.h
Labels: Ready

#1985 [Release-6.1] Transition in Receipt
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/TransactionReceipt.cpp
  src/libData/AccountData/TransactionReceipt.h
Labels: Ready

#1986 [v6.1.0] Use Buffered address when append and add DEPTH in transition field
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/TransactionReceipt.cpp
  src/libData/AccountData/TransactionReceipt.h
  tests/Data/AccountData/Test_TransactionReceipt.cpp
Labels: Ready

#1987 Use Buffered address when append and add DEPTH in transition field
  src/libData/AccountData/AccountStoreSC.h
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/TransactionReceipt.cpp
  src/libData/AccountData/TransactionReceipt.h
  tests/Data/AccountData/Test_TransactionReceipt.cpp
Labels: Ready

#1990 [release-6.1] Buffer the ret condition in multi-message loop
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#1992 [release-6.1] Adding jsonerrors flag in scilla checker command
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready

#1989 Buffer the ret condition in multi-message loop
  src/libData/AccountData/AccountStoreSC.tpp
Labels: Ready
