Repository Zilliqa/Zilliqa, pull requests merged in 2020-03, with the labels that each got.

#2011 Support zilliqa --version
  src/cmd/main.cpp
Labels: Ready, enhancement

#2014 Update link at CoC
  CODE_OF_CONDUCT.md
Labels: Ready

#2003 Adding accepted field in receipt
  src/libData/AccountData/AccountStoreSC.tpp
  src/libData/AccountData/TransactionReceipt.cpp
  src/libData/AccountData/TransactionReceipt.h
Labels: Ready

#2010 Add StakingServer
  constants.xml
  constants_local.xml
  src/common/Constants.cpp
  src/common/Constants.h
  src/libLookup/Lookup.cpp
  src/libLookup/Lookup.h
  src/libServer/CMakeLists.txt
  src/libServer/JSONConversion.cpp
  src/libServer/JSONConversion.h
  src/libServer/StakingServer.cpp
  src/libServer/StakingServer.h
  src/libZilliqa/Zilliqa.cpp
  src/libZilliqa/Zilliqa.h
Labels: Ready

#2009 Fix cseed option
  daemon/ZilliqaDaemon.cpp
Labels: Ready, bug

#2021 Remove ipMapping for dsnodes
  src/libDirectoryService/DSBlockPostProcessing.cpp
  src/libNode/Node.h
Labels: Ready

#2016 Optimize StartRetrieveHistory->RetrieveTxBlocks
  src/libData/BlockChainData/BlockChain.h
  src/libPersistence/Retriever.cpp
Labels: Ready

#2020 Send updated ds identity to upper seeds (l2ls)
  src/libDirectoryService/DirectoryService.cpp
Labels: Ready

#2022 Updated miner_info script to python3
  scripts/miner_info.py
Labels: Ready

#2012 Refactor LoadInitialDS
  src/libUtils/UpgradeManager.cpp
  src/libUtils/UpgradeManager.h
Labels: enhancement
